#' @title AutoWord2VecScoring
#'
#' @description AutoWord2VecScoring is for scoring models generated by AutoWord2VecModeler()
#'
#' @family Feature Engineering
#' @author Adrian Antico
#'
#' @param data data.table
#' @param BuildType "individual" or "combined". Used to locate model in file
#' @param ModelObject NULL if you want it loaded in the function
#' @param ModelID Same as in training
#' @param model_path Location of model
#' @param stringCol Columns to transform
#' @param KeepStringCol FALSE to remove string col after creating vectors
#' @param H2OStartUp = TRUE,
#' @param Threads max(1L, parallel::detectCores() - 2L)
#' @param MaxMemory "28G"
#'
#' @examples
#' \dontrun{
#' # Create fake data
#' data <- RemixAutoML::FakeDataGenerator(
#'   Correlation = 0.70,
#'   N = 1000L,
#'   ID = 2L,
#'   FactorCount = 2L,
#'   AddDate = TRUE,
#'   AddComment = TRUE,
#'   ZIP = 2L,
#'   TimeSeries = FALSE,
#'   ChainLadderData = FALSE,
#'   Classification = FALSE,
#'   MultiClass = FALSE)
#'
#' # Create Model and Vectors
#' data <- RemixAutoML::AutoWord2VecModeler(
#'   data,
#'   BuildType = "individual",
#'   stringCol = c("Comment"),
#'   KeepStringCol = FALSE,
#'   ModelID = "Model_1",
#'   model_path = getwd(),
#'   vects = 10,
#'   MinWords = 1,
#'   WindowSize = 1,
#'   Epochs = 25,
#'   SaveModel = "standard",
#'   Threads = max(1,parallel::detectCores()-2),
#'   MaxMemory = "28G")
#'
#' # Remove data
#' rm(data)
#'
#' # Create fake data for mock scoring
#' data <- RemixAutoML::FakeDataGenerator(
#'   Correlation = 0.70,
#'   N = 1000L,
#'   ID = 2L,
#'   FactorCount = 2L,
#'   AddDate = TRUE,
#'   AddComment = TRUE,
#'   ZIP = 2L,
#'   TimeSeries = FALSE,
#'   ChainLadderData = FALSE,
#'   Classification = FALSE,
#'   MultiClass = FALSE)
#'
#' # Create vectors for scoring
#' data <- RemixAutoML::AutoWord2VecScoring(
#'   data,
#'   BuildType = "individual",
#'   ModelObject = NULL,
#'   ModelID = "Model_1",
#'   model_path = getwd(),
#'   stringCol = "Comment",
#'   KeepStringCol = FALSE,
#'   H2OStartUp = TRUE,
#'   H2OShutdown = TRUE,
#'   Threads = max(1L, parallel::detectCores() - 2L),
#'   MaxMemory = "28G")
#' }
#'
#' @export
AutoWord2VecScoring <- function(data,
                                BuildType = "individual",
                                ModelObject = NULL,
                                ModelID = "Model_1",
                                model_path = NULL,
                                stringCol = NULL,
                                KeepStringCol = FALSE,
                                H2OStartUp = TRUE,
                                H2OShutdown = TRUE,
                                Threads = max(1L, parallel::detectCores() - 2L),
                                MaxMemory = "28G") {

  # Check args ----
  if(is.null(stringCol)) stop("stringCol cannot be NULL")
  if(is.null(ModelObject) && tolower(BuildType) == "combined" && !file.exists(file.path(model_path, ModelID))) stop(paste0("Model not found at ", file.path(model_path, ModelID)))
  if(is.null(ModelObject) && tolower(BuildType) == "individual" && !file.exists(file.path(model_path, paste0(ModelID, "_", stringCol)))) stop(paste0("Model not found at ", file.path(model_path, paste0(ModelID, "_", stringCol))))

  # Instantiate H2O ----
  if(H2OStartUp) localH2O <- h2o::h2o.init(nthreads = Threads, max_mem_size = MaxMemory, enable_assertions = FALSE)

  # Build vecs ----
  if(tolower(BuildType) == "individual") {
    for(textCol in stringCol) {
      model <- h2o::h2o.loadModel(path = file.path(model_path, paste0(ModelID, "_", textCol)))
      data1 <- AutoH2OTextPrepScoring(
        data = data,
        string = textCol,
        NThreads = Threads,
        MaxMem = MaxMemory,
        StartH2O = FALSE)
      Scores <- data.table::as.data.table(h2o::h2o.transform(
        model,
        words = data1,
        aggregate_method = "AVERAGE"))
      data.table::setnames(Scores, names(Scores), paste0(textCol, "_", names(Scores)))
      if(!KeepStringCol) {
        data[, eval(textCol) := NULL]
        data <- cbind(data, Scores)
      } else {
        data <- cbind(data, Scores)
      }
    }

  } else {
    model <- h2o::h2o.loadModel(path = file.path(model_path, ModelID))
    for(textCol in stringCol) {
      data1 <- AutoH2OTextPrepScoring(
        data = data,
        string = textCol,
        NThreads = Threads,
        MaxMem = MaxMemory,
        StartH2O = FALSE)
      Scores <- data.table::as.data.table(h2o::h2o.transform(
        model,
        words = data1,
        aggregate_method = "AVERAGE"))
      data.table::setnames(Scores, names(Scores), paste0(textCol, "_", names(Scores)))
      if(!KeepStringCol) {
        data[, eval(textCol) := NULL]
        data <- cbind(data, Scores)
      } else {
        data <- cbind(data, Scores)
      }
    }
  }

  # Remove H2O Objects ----
  rm(localH2O, model)

  # H2O Shutdown ----
  if(H2OShutdown) h2o::h2o.shutdown(prompt = FALSE)

  # Return ----
  return(data)
}
