# AutoQuant is a package for quickly creating high quality visualizations under a common and easy api.
# Copyright (C) <year>  <name of author>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

#' @title Run_ModelInsightsReport
#'
#' @description Run_ModelInsightsReport is an Rmarkdown report for viewing the model insights generated by AutoQuant supervised learning functions
#'
#' @author Adrian Antico
#' @family Reports
#'
#' @param TrainDataInclude Default FALSE. If FALSE, no derived visuals or metrics for TrainData
#' @param FeatureColumnNames NULL
#' @param SampleSize Default 100000
#' @param ModelObject Output from a AutoQuant supervised learning function
#' @param ModelID ModelID used in the AutoQuant supervised learning function
#' @param SourcePath Path to directory with DataQuant Model Output
#' @param OutputPath Path to directory where the html will be saved
#'
#' @noRd
Run_ModelInsightsReport <- function(TrainDataInclude = FALSE,
                                    FeatureColumnNames = NULL,
                                    SampleSize = 100000,
                                    ModelObject = NULL,
                                    ModelID = NULL,
                                    SourcePath = NULL,
                                    OutputPath = NULL) {

  # Directory reference
  appDir <- system.file("r-markdowns", package = "AutoQuant")

  # @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
  # Globalize the parameters
  # @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

  # ModelObject
  ModelObject <<- ModelObject

  # Finalize Passthrough
  if(!is.null(ModelObject)) {

    # DataSets
    ModelObject[['TestData']] <- ModelObject[['TestData']][order(runif(.N))][seq_len(min(.N, SampleSize))]
    if(TrainDataInclude) {
      ModelObject[['TrainData']] <- ModelObject[['TrainData']][order(runif(.N))][seq_len(min(.N, SampleSize))]
    } else {
      ModelObject[['TrainData']] <- NULL
    }

    # Meta info
    TargetType <- ModelObject[["ArgsList"]][["TargetType"]]
    if(TargetType == "Binary Classification") TargetType <- "classification"
    TargetColumnName <- ModelObject[['ArgsList']][['TargetColumnName']]
    PredictionColumnName <- ModelObject[["ArgsList"]][["PredictionColumnName"]]
    TargetLevels <- ModelObject[["ArgsList"]][["TargetLevels"]]
    Algo <- tolower(ModelObject[["ArgsList"]][["Algo"]])
    if(is.null(FeatureColumnNames)) {
      FeatureColumnNames <- ModelObject[['ColNames']][[1L]]
    }
    ArgsList <- ModelObject[['ArgsList']]

  } else {
    return(NULL)
  }

  if(length(ModelObject[['TestData']]) == 0L && length(ModelObject[['TrainData']]) == 0L) return(NULL)

  # Metadata args
  TargetType <- TargetType
  TargetLevels <- TargetLevels
  ModelID <- ModelID
  Algo <- Algo
  SourcePath <- SourcePath
  OutputPath <- OutputPath
  OutputPathName <- file.path(OutputPath, paste0('MLReport-', ModelID, '-', TargetType, '.html'))

  # @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
  # Select Rmarkdown Report and Run it
  # @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

  # Regression Markdown
  if(tolower(TargetType) == 'regression') {
    rmarkdown::render(
      input = file.path(appDir, 'Regression_ModelInsights.Rmd'),
      output_file = OutputPathName)
  }

  # Classification Markdown
  if(tolower(TargetType) == 'classification') {
    rmarkdown::render(
      input = file.path(appDir, 'Classification_ModelInsights.Rmd'),
      output_file = OutputPathName)
  }

  # MultiClass Markdown
  if(tolower(TargetType) == 'multiclass') {
    rmarkdown::render(
      input = file.path(appDir, 'MultiClass_ModelInsights.Rmd'),
      output_file = OutputPathName)
  }
}

#' @title ModelInsightsReport
#'
#' @description ModelInsightsReport is an Rmarkdown report for viewing the model insights generated by AutoQuant supervised learning functions
#'
#' @author Adrian Antico
#' @family Reports
#'
#' @param TrainDataInclude Default FALSE. If FALSE, no derived visuals or metrics for TrainData
#' @param FeatureColumnNames NULL. Feature column names as character vector.
#' @param SampleSize Default 100000
#' @param ModelObject Returned output from regression, classificaiton, and multiclass Remix Auto_() models. Currenly supports CatBoost, XGBoost, and LightGBM models
#' @param ModelID ModelID used in the AutoQuant supervised learning function
#' @param SourcePath Path to directory with AutoQuant Model Output
#' @param OutputPath Path to directory where the html will be saved
#' @param GlobalVars ls() don't use
#' @param KeepOutput NULL A list of output names to select. Pass in as a character vector. E.g. c('Test_VariableImportance', 'Train_VariableImportance')
#'
#' @export
ModelInsightsReport <- function(TrainDataInclude = FALSE,
                                FeatureColumnNames = NULL,
                                SampleSize = 100000,
                                ModelObject = NULL,
                                ModelID = 'ModelTest',
                                SourcePath = NULL,
                                OutputPath = NULL,
                                KeepOutput = NULL,
                                GlobalVars = ls()) {

  # Run Function
  Run_ModelInsightsReport(
    TrainDataInclude = TrainDataInclude,
    FeatureColumnNames = FeatureColumnNames,
    SampleSize = SampleSize,
    ModelObject = ModelObject,
    ModelID = ModelID,
    SourcePath = SourcePath,
    OutputPath = OutputPath)

  # Remove objects
  GlobalVarsNew <- ls()
  rm(list = c(setdiff(GlobalVarsNew, c(GlobalVars, KeepOutput))))
}

#' @title Run_EDA_Report
#'
#' @description Run_EDA_Report is an Rmarkdown report for EDA
#'
#' @author Adrian Antico
#' @family Reports
#'
#' @param data NULL
#' @param DataName NULL
#' @param UnivariateVars NULL
#' @param CorrVars NULL
#' @param TrendVars NULL
#' @param TrendDateVar NULL
#' @param TrendGroupVar NULL
#' @param TargetVar NULL
#' @param OutputPath Path to directory where the html will be saved
#' @param Theme AutoPlots Theme parameter value
#'
#' @noRd
Run_EDA_Report <- function(data = NULL,
                           DataName = NULL,
                           UnivariateVars = NULL,
                           CorrVars = NULL,
                           TrendVars = NULL,
                           TrendDateVar = NULL,
                           TrendGroupVar = NULL,
                           TargetVar = NULL,
                           OutputPath = NULL,
                           Theme = "dark") {

  appDir <- system.file("r-markdowns", package = "AutoQuant")
  data <- data
  UnivariateVars <- UnivariateVars
  CorrVars <- CorrVars
  TrendVars <- TrendVars
  TrendDateVar <- TrendDateVar[1]
  TrendGroupVar <- TrendGroupVar[1]
  TargetVar <- TargetVar[1]
  Theme <- Theme

  if(length(TrendDateVar) > 0L) {
    if(!class(data[[TrendDateVar]])[1L] %in% c("Date", "posix", "IDate", "IDateTime")) {
      x <- data[1L, get(TrendDateVar)]
      x1 <- lubridate::guess_formats(x, orders = c('mdY', 'BdY', 'Bdy', 'bdY', 'bdy', 'mdy', 'dby', 'Ymd', 'Ydm', 'dmy'))
      data[, eval(TrendDateVar) := as.Date(get(TrendDateVar), tryFormats = x1)]
      if(!class(data[[TrendDateVar]])[1L] %in% c("Date", "posix", "IDate", "IDateTime")) {
        TrendDateVar <- NULL
      }
    }
  }

  OutputPathName <- file.path(OutputPath, paste0('EDAReport-', DataName, '.html'))
  rmarkdown::render(
    input = file.path(appDir, 'EDA_Report.Rmd'),
    output_file = OutputPathName
  )
}

#' @title Exploratory Data Analysis Report
#'
#' @description
#' Generates an HTML R Markdown exploratory data analysis report for a supplied
#' dataset. The report includes dataset-level diagnostics, univariate summaries,
#' univariate plots, correlation analysis, trend analysis, and optional
#' target-oriented diagnostics when a target variable is supplied.
#'
#' The report is designed to provide a broad pre-modeling view of data quality,
#' variable distributions, relationships between numeric variables, temporal
#' movement, grouped trend behavior, target associations, feature drift, concept
#' drift, and potential leakage or collider-risk indicators.
#'
#' @author Adrian Antico
#'
#' @family Reports
#'
#' @param data A data.frame or data.table containing the dataset to profile.
#' @param DataName Optional character value used as the display name for the
#'   dataset in the report.
#' @param UnivariateVars Optional character vector of variables to include in
#'   the univariate statistics and univariate plot sections. If NULL, variables
#'   are selected from the supplied dataset based on supported data types.
#' @param CorrVars Optional character vector of variables to include in the
#'   correlation analysis section. Non-numeric, missing, and constant variables
#'   are diagnosed and skipped where appropriate.
#' @param TrendVars Optional character vector of numeric variables to include in
#'   the trend analysis section.
#' @param TrendDateVar Optional character value identifying the date or datetime
#'   variable used to aggregate trend plots and drift diagnostics.
#' @param TrendGroupVar Optional character value identifying a grouping variable
#'   used to split grouped trend plots, grouped target trends, and grouped
#'   distribution diagnostics where applicable.
#' @param TargetVar Optional character value identifying the target variable for
#'   target-oriented analysis. When supplied, the report creates target QA,
#'   target distribution summaries, target association diagnostics, target trend
#'   diagnostics, feature drift diagnostics, concept drift diagnostics, and
#'   potential leakage, collider, or post-treatment risk flags.
#' @param OutputPath Character value specifying the directory or file path where
#'   the rendered report should be written.
#' @param Theme Character value passed to AutoPlots plotting functions to control
#'   the visual theme of generated plots.
#'
#' @return
#' Invisibly returns the output path of the rendered report. The primary side
#' effect is an HTML EDA report written to `OutputPath`.
#'
#' @details
#' The report contains the following major sections:
#'
#' \itemize{
#'   \item Data description and column-level diagnostics
#'   \item Univariate statistics
#'   \item Univariate distribution, box, grouped box, discrete numeric, and categorical plots
#'   \item Correlation input diagnostics, pairwise correlation statistics, and correlation plots
#'   \item Overall trend area plots and grouped trend line plots
#'   \item Optional target-oriented analysis when `TargetVar` is supplied
#' }
#'
#' Target-oriented analysis supports binary, multiclass, and continuous target
#' variables where possible. The diagnostics are intended to surface useful
#' modeling signals and risks, but leakage, collider, and concept drift flags are
#' heuristic indicators and should be reviewed before being treated as causal or
#' definitive.
#'
#' @export
EDAReport <- function(data = NULL,
                      DataName = NULL,
                      UnivariateVars = NULL,
                      CorrVars = NULL,
                      TrendVars = NULL,
                      TrendDateVar = NULL,
                      TrendGroupVar = NULL,
                      TargetVar = NULL,
                      OutputPath = NULL,
                      Theme = "dark") {

  Run_EDA_Report(
    data = data,
    DataName = DataName,
    UnivariateVars = UnivariateVars,
    CorrVars = CorrVars,
    TrendVars = TrendVars,
    TrendDateVar = TrendDateVar,
    TrendGroupVar = TrendGroupVar,
    TargetVar = TargetVar,
    OutputPath = OutputPath,
    Theme = Theme
  )
}
