# AutoQuant is a package for quickly creating high quality visualizations under a common and easy api.
# Copyright (C) <year>  <name of author>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

#' @title Run_ModelInsightsReport
#'
#' @description Run_ModelInsightsReport is an Rmarkdown report for viewing the model insights generated by AutoQuant supervised learning functions
#'
#' @author Adrian Antico
#' @family Reports
#'
#' @param TrainDataInclude Default FALSE. If FALSE, no derived visuals or metrics for TrainData
#' @param FeatureColumnNames NULL
#' @param SampleSize Default 100000
#' @param ModelObject Output from a AutoQuant supervised learning function
#' @param ModelID ModelID used in the AutoQuant supervised learning function
#' @param SourcePath Path to directory with DataQuant Model Output
#' @param OutputPath Path to directory where the html will be saved
#'
#' @noRd
Run_ModelInsightsReport <- function(TrainDataInclude = FALSE,
                                    FeatureColumnNames = NULL,
                                    SampleSize = 100000,
                                    ModelObject = NULL,
                                    ModelID = NULL,
                                    SourcePath = NULL,
                                    OutputPath = NULL) {

  # Directory reference
  appDir <- system.file("r-markdowns", package = "AutoQuant")

  # @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
  # Globalize the parameters
  # @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

  # ModelObject
  ModelObject <<- ModelObject

  # Finalize Passthrough
  if(!is.null(ModelObject)) {

    # DataSets
    ModelObject[['TestData']] <- ModelObject[['TestData']][order(runif(.N))][seq_len(min(.N, SampleSize))]
    if(TrainDataInclude) {
      ModelObject[['TrainData']] <- ModelObject[['TrainData']][order(runif(.N))][seq_len(min(.N, SampleSize))]
    } else {
      ModelObject[['TrainData']] <- NULL
    }

    # Meta info
    TargetType <- ModelObject[["ArgsList"]][["TargetType"]]
    if(TargetType == "Binary Classification") TargetType <- "classification"
    TargetColumnName <- ModelObject[['ArgsList']][['TargetColumnName']]
    PredictionColumnName <- ModelObject[["ArgsList"]][["PredictionColumnName"]]
    TargetLevels <- ModelObject[["ArgsList"]][["TargetLevels"]]
    Algo <- tolower(ModelObject[["ArgsList"]][["Algo"]])
    if(is.null(FeatureColumnNames)) {
      FeatureColumnNames <- ModelObject[['ColNames']][[1L]]
    }
    ArgsList <- ModelObject[['ArgsList']]

  } else {
    return(NULL)
  }

  if(length(ModelObject[['TestData']]) == 0L && length(ModelObject[['TrainData']]) == 0L) return(NULL)

  # Metadata args
  TargetType <- TargetType
  TargetLevels <- TargetLevels
  ModelID <- ModelID
  Algo <- Algo
  SourcePath <- SourcePath
  OutputPath <- OutputPath
  OutputPathName <- file.path(OutputPath, paste0('MLReport-', ModelID, '-', TargetType, '.html'))

  # @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
  # Select Rmarkdown Report and Run it
  # @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

  # Regression Markdown
  if(tolower(TargetType) == 'regression') {
    rmarkdown::render(
      input = file.path(appDir, 'Regression_ModelInsights.Rmd'),
      output_file = OutputPathName)
  }

  # Classification Markdown
  if(tolower(TargetType) == 'classification') {
    rmarkdown::render(
      input = file.path(appDir, 'Classification_ModelInsights.Rmd'),
      output_file = OutputPathName)
  }

  # MultiClass Markdown
  if(tolower(TargetType) == 'multiclass') {
    rmarkdown::render(
      input = file.path(appDir, 'MultiClass_ModelInsights.Rmd'),
      output_file = OutputPathName)
  }
}

#' @title ModelInsightsReport
#'
#' @description
#' Legacy RMarkdown report for model insights generated by AutoQuant supervised
#' learning functions. Prefer the artifact-first report functions:
#' `RegressionModelInsightsReport()` for regression and
#' `BinaryClassificationModelInsightsReport()` for binary classification.
#'
#' @author Adrian Antico
#' @family Reports
#'
#' @param TrainDataInclude Default FALSE. If FALSE, no derived visuals or metrics for TrainData
#' @param FeatureColumnNames NULL. Feature column names as character vector.
#' @param SampleSize Default 100000
#' @param ModelObject Returned output from regression, classificaiton, and multiclass Remix Auto_() models. Currenly supports CatBoost, XGBoost, and LightGBM models
#' @param ModelID ModelID used in the AutoQuant supervised learning function
#' @param SourcePath Path to directory with AutoQuant Model Output
#' @param OutputPath Path to directory where the html will be saved
#' @param GlobalVars ls() don't use
#' @param KeepOutput NULL A list of output names to select. Pass in as a character vector. E.g. c('Test_VariableImportance', 'Train_VariableImportance')
#'
#' @export
ModelInsightsReport <- function(TrainDataInclude = FALSE,
                                FeatureColumnNames = NULL,
                                SampleSize = 100000,
                                ModelObject = NULL,
                                ModelID = 'ModelTest',
                                SourcePath = NULL,
                                OutputPath = NULL,
                                KeepOutput = NULL,
                                GlobalVars = ls()) {

  # Run Function
  Run_ModelInsightsReport(
    TrainDataInclude = TrainDataInclude,
    FeatureColumnNames = FeatureColumnNames,
    SampleSize = SampleSize,
    ModelObject = ModelObject,
    ModelID = ModelID,
    SourcePath = SourcePath,
    OutputPath = OutputPath)

  # Remove objects
  GlobalVarsNew <- ls()
  rm(list = c(setdiff(GlobalVarsNew, c(GlobalVars, KeepOutput))))
}

aq_report_default <- function(value, default) {
  if (is.null(value)) default else value
}

aq_report_pop_arg <- function(args, names, default = NULL) {
  for (nm in names) {
    if (nm %in% names(args)) {
      return(args[[nm]])
    }
  }
  default
}

aq_report_drop_args <- function(args, names) {
  args[setdiff(names(args), names)]
}

aq_report_render_options <- function(
  dots,
  OutputPath,
  OutputFile,
  Title,
  Subtitle,
  Theme,
  Open,
  Quiet,
  default_output_file,
  default_rmd_file,
  default_self_contained = TRUE
) {
  render_names <- c(
    "OutputPath", "output_path", "output_dir",
    "OutputFile", "output_file",
    "Title", "title",
    "Subtitle", "subtitle",
    "Theme", "theme",
    "Open", "open",
    "Quiet", "quiet",
    "SelfContained", "self_contained",
    "RmdFile", "Package", "TemplatePath", "Clean", "Envir"
  )

  output_path <- aq_report_pop_arg(dots, c("OutputPath", "output_path", "output_dir"), OutputPath)
  output_file <- aq_report_pop_arg(dots, c("OutputFile", "output_file"), OutputFile)
  title <- aq_report_pop_arg(dots, c("Title", "title"), Title)
  subtitle <- aq_report_pop_arg(dots, c("Subtitle", "subtitle"), Subtitle)
  theme <- aq_report_pop_arg(dots, c("Theme", "theme"), Theme)
  open <- aq_report_pop_arg(dots, c("Open", "open"), Open)
  quiet <- aq_report_pop_arg(dots, c("Quiet", "quiet"), Quiet)
  self_contained <- aq_report_pop_arg(dots, c("SelfContained", "self_contained"), default_self_contained)
  rmd_file <- aq_report_pop_arg(dots, "RmdFile", default_rmd_file)
  package <- aq_report_pop_arg(dots, "Package", "AutoQuant")
  template_path <- aq_report_pop_arg(dots, "TemplatePath", NULL)
  clean <- aq_report_pop_arg(dots, "Clean", TRUE)
  envir <- aq_report_pop_arg(dots, "Envir", NULL)
  generator_args <- aq_report_drop_args(dots, render_names)

  if (is.null(output_file) || !nzchar(output_file)) {
    output_file <- default_output_file
  }
  if (!grepl("\\.html?$", output_file, ignore.case = TRUE)) {
    output_file <- paste0(output_file, ".html")
  }
  if (!("Theme" %in% names(generator_args))) {
    generator_args$Theme <- theme
  }

  list(
    OutputPath = aq_report_default(output_path, getwd()),
    OutputFile = output_file,
    Title = title,
    Subtitle = subtitle,
    Theme = theme,
    Open = open,
    Quiet = quiet,
    SelfContained = self_contained,
    RmdFile = rmd_file,
    Package = package,
    TemplatePath = template_path,
    Clean = clean,
    Envir = envir,
    generator_args = generator_args
  )
}

aq_report_template_path <- function(RmdFile, Package = "AutoQuant", TemplatePath = NULL) {
  if (!is.null(TemplatePath) && nzchar(TemplatePath)) {
    template_path <- normalizePath(TemplatePath, winslash = "/", mustWork = FALSE)
  } else {
    template_path <- system.file("r-markdowns", RmdFile, package = Package)
    if (!nzchar(template_path) || !file.exists(template_path)) {
      template_path <- normalizePath(file.path(getwd(), "inst", "r-markdowns", RmdFile), winslash = "/", mustWork = FALSE)
    }
    if (!file.exists(template_path)) {
      template_path <- normalizePath(file.path(getwd(), RmdFile), winslash = "/", mustWork = FALSE)
    }
  }

  if (!file.exists(template_path)) {
    stop(
      paste0(
        "RMarkdown template not found. Expected one of:\n",
        "1. ", file.path("inst", "r-markdowns", RmdFile), "\n",
        "2. system.file('r-markdowns', '", RmdFile, "', package = '", Package, "')\n",
        "3. Explicit `TemplatePath`."
      ),
      call. = FALSE
    )
  }

  template_path
}

aq_report_safe_name <- function(value, default) {
  value <- aq_report_default(value, default)
  value <- as.character(value[1L])
  if (is.na(value) || !nzchar(value)) {
    value <- default
  }
  safe <- gsub("[^A-Za-z0-9_-]+", "_", value)
  safe <- gsub("_+", "_", safe)
  safe <- gsub("^_|_$", "", safe)
  if (!nzchar(safe)) default else safe
}

aq_report_validate_artifact_result <- function(artifact_result, generator_name) {
  has_artifact_payload <- is.list(artifact_result) && (
    !is.null(artifact_result$artifacts) ||
      !is.null(artifact_result$tables) ||
      !is.null(artifact_result$plots) ||
      inherits(artifact_result, "autoquant_report_artifacts")
  )
  if (!has_artifact_payload) {
    stop(
      paste0("`artifact_result` must be the structured output from ", generator_name, "()."),
      call. = FALSE
    )
  }
  invisible(TRUE)
}

aq_report_render <- function(
  artifact_result,
  opts,
  template_params = list(),
  env_names = character()
) {
  if (!requireNamespace("rmarkdown", quietly = TRUE)) {
    stop("Package 'rmarkdown' is required to render AutoQuant reports.", call. = FALSE)
  }

  output_dir <- normalizePath(opts$OutputPath, winslash = "/", mustWork = FALSE)
  dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
  template_path <- aq_report_template_path(opts$RmdFile, opts$Package, opts$TemplatePath)

  Envir <- opts$Envir
  if (is.null(Envir)) {
    Envir <- new.env(parent = .GlobalEnv)
  }

  assign("artifact_result", artifact_result, envir = Envir)
  assign("artifacts", artifact_result, envir = Envir)
  for (nm in env_names) {
    assign(nm, artifact_result, envir = Envir)
  }

  rendered_file <- rmarkdown::render(
    input = template_path,
    output_file = opts$OutputFile,
    output_dir = output_dir,
    params = template_params,
    envir = Envir,
    quiet = opts$Quiet,
    clean = opts$Clean,
    output_options = list(self_contained = isTRUE(opts$SelfContained))
  )

  rendered_file <- normalizePath(rendered_file, winslash = "/", mustWork = FALSE)
  attr(rendered_file, "artifact_result") <- artifact_result
  if (isTRUE(opts$Open)) {
    utils::browseURL(rendered_file)
  }

  invisible(rendered_file)
}

#' Render Exploratory Data Analysis Report
#'
#' Renders an HTML EDA report from a pre-generated artifact result. If
#' `artifact_result` is not supplied, this function calls
#' `generate_eda_artifacts(data = data, ...)` as a convenience wrapper.
#'
#' @param artifact_result Optional result returned by `generate_eda_artifacts()`.
#' @param data Optional source data used only when `artifact_result` is NULL.
#' @param OutputPath Directory where the rendered report should be written.
#' @param OutputFile Optional output HTML filename.
#' @param Title Optional report/data title. Used as `DataName` for the template
#'   and default filename.
#' @param Subtitle Optional report subtitle. Reserved for report templates that
#'   support it.
#' @param Theme Report theme.
#' @param Open If TRUE, open the rendered report.
#' @param Quiet Passed to `rmarkdown::render()`.
#' @param ... Analytical arguments passed to `generate_eda_artifacts()` when
#'   `artifact_result` is NULL, plus optional render controls `SelfContained`,
#'   `RmdFile`, `Package`, `TemplatePath`, `Clean`, and `Envir`.
#'
#' @return Invisibly returns the rendered report path.
#'
#' @family Reports
#' @export
EDAReport <- function(
  artifact_result = NULL,
  data = NULL,
  OutputPath = getwd(),
  OutputFile = NULL,
  Title = NULL,
  Subtitle = NULL,
  Theme = "dark",
  Open = FALSE,
  Quiet = TRUE,
  ...
) {
  opts <- aq_report_render_options(
    dots = list(...),
    OutputPath = OutputPath,
    OutputFile = OutputFile,
    Title = Title,
    Subtitle = Subtitle,
    Theme = Theme,
    Open = Open,
    Quiet = Quiet,
    default_output_file = "EDAReport.html",
    default_rmd_file = "EDA_Report.Rmd"
  )

  if (is.null(artifact_result)) {
    if (is.null(data)) {
      stop("`data` must be supplied when `artifact_result` is NULL.", call. = FALSE)
    }
    artifact_result <- do.call(generate_eda_artifacts, c(list(data = data), opts$generator_args))
  }
  aq_report_validate_artifact_result(artifact_result, "generate_eda_artifacts")

  data_name <- aq_report_default(opts$Title, tryCatch(artifact_result$metadata$DataName, error = function(e) NULL))
  data_name <- aq_report_default(data_name, "EDA Data")
  if (identical(opts$OutputFile, "EDAReport.html")) {
    opts$OutputFile <- paste0("EDAReport-", aq_report_safe_name(data_name, "EDA_Data"), ".html")
  }

  aq_report_render(
    artifact_result = artifact_result,
    opts = opts,
    template_params = list(
      artifacts = artifact_result,
      DataName = as.character(data_name[1L]),
      Theme = opts$Theme
    ),
    env_names = "EDAArtifacts"
  )
}

#' Render Model Readiness / Target Analysis Report
#'
#' Renders the target analysis / model readiness report from pre-generated
#' artifacts. If `artifact_result` is not supplied, this function calls
#' `generate_model_assessment_artifacts(data = data, ...)` as a convenience
#' wrapper. The report name is retained for transition; the product terminology
#' should move toward Model Readiness for pre-model diagnostics.
#'
#' @param artifact_result Optional result returned by
#'   `generate_model_assessment_artifacts()`.
#' @param data Optional source data used only when `artifact_result` is NULL.
#' @param OutputPath Directory where the rendered report should be written.
#' @param OutputFile Optional output HTML filename.
#' @param Title Optional report/data title. Used as `DataName` for the template
#'   and default filename.
#' @param Subtitle Optional report subtitle. Reserved for report templates that
#'   support it.
#' @param Theme Report theme.
#' @param Open If TRUE, open the rendered report.
#' @param Quiet Passed to `rmarkdown::render()`.
#' @param ... Analytical arguments passed to
#'   `generate_model_assessment_artifacts()` when `artifact_result` is NULL,
#'   plus optional render controls `SelfContained`, `RmdFile`, `Package`,
#'   `TemplatePath`, `Clean`, and `Envir`.
#'
#' @return Invisibly returns the rendered report path.
#'
#' @family Reports
#' @export
TargetAnalysisReport <- function(
  artifact_result = NULL,
  data = NULL,
  OutputPath = getwd(),
  OutputFile = NULL,
  Title = NULL,
  Subtitle = NULL,
  Theme = "dark",
  Open = FALSE,
  Quiet = TRUE,
  ...
) {
  opts <- aq_report_render_options(
    dots = list(...),
    OutputPath = OutputPath,
    OutputFile = OutputFile,
    Title = Title,
    Subtitle = Subtitle,
    Theme = Theme,
    Open = Open,
    Quiet = Quiet,
    default_output_file = "TargetAnalysis.html",
    default_rmd_file = "Target_Analysis_Report.Rmd"
  )

  if (is.null(artifact_result)) {
    if (is.null(data)) {
      stop("`data` must be supplied when `artifact_result` is NULL.", call. = FALSE)
    }
    artifact_result <- do.call(generate_model_assessment_artifacts, c(list(data = data), opts$generator_args))
  }
  aq_report_validate_artifact_result(artifact_result, "generate_model_assessment_artifacts")

  data_name <- aq_report_default(opts$Title, tryCatch(artifact_result$metadata$DataName, error = function(e) NULL))
  data_name <- aq_report_default(data_name, "Modeling Data")
  if (identical(opts$OutputFile, "TargetAnalysis.html")) {
    opts$OutputFile <- paste0("TargetAnalysis-", aq_report_safe_name(data_name, "Modeling_Data"), ".html")
  }

  aq_report_render(
    artifact_result = artifact_result,
    opts = opts,
    template_params = list(
      artifacts = artifact_result,
      DataName = as.character(data_name[1L]),
      Theme = opts$Theme
    ),
    env_names = "TargetAnalysisArtifacts"
  )
}

# ============================================================
# Render Regression Model Insights Report from Artifacts
#
# RMarkdown template expected at:
#   inst/r-markdowns/Regression_ModelInsights_Artifact_Renderer.Rmd
#
# This function intentionally does only one thing:
#   take a precomputed artifacts object and render the report.
# ============================================================

#' Render Regression Model Insights Report
#'
#' Renders regression model-insights artifacts. If `artifact_result` is not
#' supplied, this function calls
#' `generate_regression_model_insights_artifacts()` as a convenience wrapper.
#' Analytical arguments belong to the generator and pass through `...`.
#'
#' @param artifact_result Optional result returned by
#'   `generate_regression_model_insights_artifacts()`.
#' @param data Optional scored/test data used only when `artifact_result` is
#'   NULL. It is passed to the generator as `TestData` unless `TestData` is
#'   explicitly supplied through `...`.
#' @param OutputPath Directory where the rendered report should be written.
#' @param OutputFile Optional output HTML filename.
#' @param Title Optional report title. Reserved for templates that support it.
#' @param Subtitle Optional report subtitle. Reserved for templates that support
#'   it.
#' @param Theme Report theme.
#' @param Open If TRUE, open the rendered report.
#' @param Quiet Passed to `rmarkdown::render()`.
#' @param ... Analytical arguments passed to
#'   `generate_regression_model_insights_artifacts()` when `artifact_result` is
#'   NULL, plus optional render controls `SelfContained`, `RmdFile`, `Package`,
#'   `TemplatePath`, `Clean`, and `Envir`.
#'
#' @return Invisibly returns the rendered report path.
#'
#' @family Reports
#' @export
RegressionModelInsightsReport <- function(
  artifact_result = NULL,
  data = NULL,
  OutputPath = getwd(),
  OutputFile = NULL,
  Title = NULL,
  Subtitle = NULL,
  Theme = "dark",
  Open = FALSE,
  Quiet = TRUE,
  ...
) {
  opts <- aq_report_render_options(
    dots = list(...),
    OutputPath = OutputPath,
    OutputFile = OutputFile,
    Title = Title,
    Subtitle = Subtitle,
    Theme = Theme,
    Open = Open,
    Quiet = Quiet,
    default_output_file = "Regression_ModelInsights_Report.html",
    default_rmd_file = "Regression_ModelInsights_Artifact_Renderer.Rmd"
  )

  if (is.null(artifact_result)) {
    if (is.null(data) && is.null(opts$generator_args$TestData) && is.null(opts$generator_args$ModelObject)) {
      stop("Supply `artifact_result`, or supply `data`/`TestData` plus generator arguments.", call. = FALSE)
    }
    if (!is.null(data) && is.null(opts$generator_args$TestData)) {
      opts$generator_args$TestData <- data
    }
    artifact_result <- do.call(generate_regression_model_insights_artifacts, opts$generator_args)
  }
  aq_report_validate_artifact_result(artifact_result, "generate_regression_model_insights_artifacts")

  aq_report_render(
    artifact_result = artifact_result,
    opts = opts,
    template_params = list(
      artifacts = artifact_result,
      Theme = opts$Theme
    ),
    env_names = "ModelInsightsArtifacts"
  )
}

# ============================================================
# Render Binary Classification Model Insights Report from Artifacts
#
# RMarkdown template expected at:
#   inst/r-markdowns/Binary_Classification_ModelInsights_Artifact_Renderer.Rmd
# ============================================================

#' Render Binary Classification Model Insights Report
#'
#' Renders binary classification model-insights artifacts. If `artifact_result`
#' is not supplied, this function calls
#' `generate_binary_classification_model_insights_artifacts(data = data, ...)`
#' as a convenience wrapper. Analytical arguments belong to the generator and
#' pass through `...`.
#'
#' @param artifact_result Optional result returned by
#'   `generate_binary_classification_model_insights_artifacts()`.
#' @param data Optional scored/model-output data used only when
#'   `artifact_result` is NULL.
#' @param OutputPath Directory where the rendered report should be written.
#' @param OutputFile Optional output HTML filename.
#' @param Title Optional report title. Reserved for templates that support it.
#' @param Subtitle Optional report subtitle. Reserved for templates that support
#'   it.
#' @param Theme Report theme.
#' @param Open If TRUE, open the rendered report.
#' @param Quiet Passed to `rmarkdown::render()`.
#' @param ... Analytical arguments passed to
#'   `generate_binary_classification_model_insights_artifacts()` when
#'   `artifact_result` is NULL, plus optional render controls `SelfContained`,
#'   `RmdFile`, `Package`, `TemplatePath`, `Clean`, and `Envir`.
#'
#' @return Invisibly returns the rendered report path.
#'
#' @family Reports
#' @export
BinaryClassificationModelInsightsReport <- function(
  artifact_result = NULL,
  data = NULL,
  OutputPath = getwd(),
  OutputFile = NULL,
  Title = NULL,
  Subtitle = NULL,
  Theme = "dark",
  Open = FALSE,
  Quiet = TRUE,
  ...
) {
  opts <- aq_report_render_options(
    dots = list(...),
    OutputPath = OutputPath,
    OutputFile = OutputFile,
    Title = Title,
    Subtitle = Subtitle,
    Theme = Theme,
    Open = Open,
    Quiet = Quiet,
    default_output_file = "Binary_Classification_ModelInsights_Report.html",
    default_rmd_file = "Binary_Classification_ModelInsights_Artifact_Renderer.Rmd"
  )

  if (is.null(artifact_result)) {
    if (is.null(data)) {
      stop("`data` must be supplied when `artifact_result` is NULL.", call. = FALSE)
    }
    artifact_result <- do.call(
      generate_binary_classification_model_insights_artifacts,
      c(list(data = data), opts$generator_args)
    )
  }
  aq_report_validate_artifact_result(artifact_result, "generate_binary_classification_model_insights_artifacts")

  aq_report_render(
    artifact_result = artifact_result,
    opts = opts,
    template_params = list(artifacts = artifact_result),
    env_names = "BinaryClassificationModelInsightsArtifacts"
  )
}

# ============================================================
# Render Regression SHAP Analysis Report from Artifacts
#
# RMarkdown template expected at:
#   inst/r-markdowns/Regression_SHAP_Analysis_Report.Rmd
#
# This function renders the AutoQuant-native standalone report path. It calls
# generate_regression_shap_analysis_artifacts() when artifact_result is not
# supplied, but it does not compute SHAP values itself.
# ============================================================

aq_shap_report_pop_arg <- function(args, names, default = NULL) {
  for (nm in names) {
    if (nm %in% names(args)) {
      return(args[[nm]])
    }
  }
  default
}

aq_shap_report_drop_args <- function(args, names) {
  args[setdiff(names(args), names)]
}

aq_shap_report_default <- function(value, default) {
  if (is.null(value)) default else value
}

aq_shap_report_options <- function(
  dots,
  OutputPath,
  OutputFile,
  Title,
  Subtitle,
  Theme,
  Open,
  Quiet,
  default_output_file,
  default_rmd_file
) {
  render_names <- c(
    "OutputPath", "output_path", "output_dir",
    "OutputFile", "output_file",
    "Title", "title",
    "Subtitle", "subtitle",
    "Theme", "theme",
    "Open", "open",
    "Quiet", "quiet",
    "SelfContained", "self_contained",
    "RmdFile", "Package", "TemplatePath", "Clean", "Envir"
  )

  output_path <- aq_shap_report_pop_arg(dots, c("OutputPath", "output_path", "output_dir"), OutputPath)
  output_file <- aq_shap_report_pop_arg(dots, c("OutputFile", "output_file"), OutputFile)
  title <- aq_shap_report_pop_arg(dots, c("Title", "title"), Title)
  subtitle <- aq_shap_report_pop_arg(dots, c("Subtitle", "subtitle"), Subtitle)
  theme <- aq_shap_report_pop_arg(dots, c("Theme", "theme"), Theme)
  open <- aq_shap_report_pop_arg(dots, c("Open", "open"), Open)
  quiet <- aq_shap_report_pop_arg(dots, c("Quiet", "quiet"), Quiet)
  self_contained <- aq_shap_report_pop_arg(dots, c("SelfContained", "self_contained"), TRUE)
  rmd_file <- aq_shap_report_pop_arg(dots, "RmdFile", default_rmd_file)
  package <- aq_shap_report_pop_arg(dots, "Package", "AutoQuant")
  template_path <- aq_shap_report_pop_arg(dots, "TemplatePath", NULL)
  clean <- aq_shap_report_pop_arg(dots, "Clean", TRUE)
  envir <- aq_shap_report_pop_arg(dots, "Envir", NULL)
  generator_args <- aq_shap_report_drop_args(dots, render_names)

  if (is.null(output_file) || !nzchar(output_file)) {
    output_file <- default_output_file
  }
  if (!grepl("\\.html?$", output_file, ignore.case = TRUE)) {
    output_file <- paste0(output_file, ".html")
  }

  if (!("auto_plots_theme" %in% names(generator_args))) {
    generator_args$auto_plots_theme <- theme
  }

  list(
    OutputPath = output_path,
    OutputFile = output_file,
    Title = title,
    Subtitle = subtitle,
    Theme = theme,
    Open = open,
    Quiet = quiet,
    SelfContained = self_contained,
    RmdFile = rmd_file,
    Package = package,
    TemplatePath = template_path,
    Clean = clean,
    Envir = envir,
    generator_args = generator_args
  )
}

aq_shap_report_template_path <- function(RmdFile, Package, TemplatePath = NULL) {
  if (!is.null(TemplatePath) && nzchar(TemplatePath)) {
    template_path <- normalizePath(TemplatePath, winslash = "/", mustWork = FALSE)
  } else {
    template_path <- system.file("r-markdowns", RmdFile, package = Package)
    if (!nzchar(template_path) || !file.exists(template_path)) {
      template_path <- file.path(getwd(), "inst", "r-markdowns", RmdFile)
      template_path <- normalizePath(template_path, winslash = "/", mustWork = FALSE)
    }
  }
  if (!file.exists(template_path)) {
    template_path <- file.path(getwd(), RmdFile)
    template_path <- normalizePath(template_path, winslash = "/", mustWork = FALSE)
  }
  if (!file.exists(template_path)) {
    stop(
      paste0(
        "RMarkdown template not found. Expected one of:\n",
        "1. ", file.path("inst", "r-markdowns", RmdFile), "\n",
        "2. system.file('r-markdowns', '", RmdFile, "', package = '", Package, "')\n",
        "3. Explicit `TemplatePath`."
      ),
      call. = FALSE
    )
  }
  template_path
}

aq_prepare_regression_shap_report_artifact_result <- function(data = NULL, artifact_result = NULL, generator_args = list()) {
  if (!is.null(artifact_result)) {
    return(artifact_result)
  }
  if (is.null(data)) {
    stop("`data` must be supplied when `artifact_result` is NULL.", call. = FALSE)
  }
  do.call(
    generate_regression_shap_analysis_artifacts,
    c(list(data = data), generator_args)
  )
}

aq_prepare_binary_shap_report_artifact_result <- function(data = NULL, artifact_result = NULL, generator_args = list()) {
  if (!is.null(artifact_result)) {
    return(artifact_result)
  }
  if (is.null(data)) {
    stop("`data` must be supplied when `artifact_result` is NULL.", call. = FALSE)
  }
  do.call(
    generate_binary_classification_shap_analysis_artifacts,
    c(list(data = data), generator_args)
  )
}

aq_validate_shap_report_artifact_result <- function(artifact_result, generator_name) {
  if (!is.list(artifact_result) || is.null(artifact_result$artifacts)) {
    stop(
      paste0("`artifact_result` must be the structured output from ", generator_name, "()."),
      call. = FALSE
    )
  }
  invisible(TRUE)
}

#' Render Regression SHAP Analysis Report
#'
#' Renders a standalone AutoQuant-native HTML report from Regression SHAP
#' Analysis artifacts. If `artifact_result` is not supplied, this function calls
#' `generate_regression_shap_analysis_artifacts()` first. Input data must contain
#' precomputed `Shap_` columns; this report function does not compute SHAP
#' values, call `predict()`, require a model object, or use a SHAP backend
#' package.
#'
#' @param data Optional data.table containing precomputed `Shap_` columns. Used
#'   only when `artifact_result` is NULL.
#' @param artifact_result Optional precomputed result returned by
#'   `generate_regression_shap_analysis_artifacts()`.
#' @param OutputPath Directory where the rendered report should be written.
#' @param OutputFile Output HTML filename.
#' @param Title Report title.
#' @param Subtitle Optional report subtitle.
#' @param Theme Report theme label stored in render params. If `auto_plots_theme`
#'   is not supplied through `...`, this value is also passed to the artifact
#'   generator as `auto_plots_theme`.
#' @param Open If TRUE, open the rendered report in a browser.
#' @param Quiet Passed to `rmarkdown::render()`.
#' @param ... Analytical arguments passed to
#'   `generate_regression_shap_analysis_artifacts()` when `artifact_result` is
#'   NULL, plus optional render controls `self_contained`, `RmdFile`, `Package`,
#'   `TemplatePath`, `Clean`, and `Envir`. Legacy lowercase render names such as
#'   `output_dir`, `output_file`, `title`, `subtitle`, `open`, and `quiet` are
#'   still accepted.
#'
#' @return Invisibly returns the rendered report path.
#'
#' @family Reports
#' @export
RegressionShapAnalysisReport <- function(
  artifact_result = NULL,
  data = NULL,
  OutputPath = getwd(),
  OutputFile = NULL,
  Title = "Regression SHAP Analysis Report",
  Subtitle = NULL,
  Theme = "dark",
  Open = FALSE,
  Quiet = TRUE,
  ...
) {
  if (!requireNamespace("rmarkdown", quietly = TRUE)) {
    stop("Package 'rmarkdown' is required to render RegressionShapAnalysisReport().", call. = FALSE)
  }

  if (!requireNamespace("knitr", quietly = TRUE)) {
    stop("Package 'knitr' is required to render RegressionShapAnalysisReport().", call. = FALSE)
  }

  for (pkg in c("data.table", "htmltools", "reactable", "echarts4r", "AutoPlots")) {
    if (!requireNamespace(pkg, quietly = TRUE)) {
      stop(paste0("Package '", pkg, "' is required to render RegressionShapAnalysisReport()."), call. = FALSE)
    }
  }

  opts <- aq_shap_report_options(
    dots = list(...),
    OutputPath = OutputPath,
    OutputFile = OutputFile,
    Title = Title,
    Subtitle = Subtitle,
    Theme = Theme,
    Open = Open,
    Quiet = Quiet,
    default_output_file = "regression_shap_analysis_report.html",
    default_rmd_file = "Regression_SHAP_Analysis_Report.Rmd"
  )

  artifact_result <- aq_prepare_regression_shap_report_artifact_result(
    data = data,
    artifact_result = artifact_result,
    generator_args = opts$generator_args
  )
  aq_validate_shap_report_artifact_result(artifact_result, "generate_regression_shap_analysis_artifacts")

  output_dir <- normalizePath(opts$OutputPath, winslash = "/", mustWork = FALSE)
  dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)

  template_path <- aq_shap_report_template_path(opts$RmdFile, opts$Package, opts$TemplatePath)

  generated_at <- artifact_result$metadata$generated_at
  if (is.null(generated_at)) {
    generated_at <- Sys.time()
  }

  Envir <- opts$Envir
  if (is.null(Envir)) {
    Envir <- new.env(parent = .GlobalEnv)
  }
  assign("artifact_result", artifact_result, envir = Envir)
  assign("RegressionShapArtifacts", artifact_result, envir = Envir)

  rendered_file <- rmarkdown::render(
    input = template_path,
    output_file = opts$OutputFile,
    output_dir = output_dir,
    params = list(
      title = opts$Title,
      subtitle = opts$Subtitle,
      Theme = opts$Theme,
      generated_at = generated_at,
      artifact_result = artifact_result,
      artifact_sections = regression_shap_sections(),
      metadata = artifact_result$metadata,
      warnings = artifact_result$warnings,
      diagnostics = artifact_result$diagnostics,
      top_n = aq_shap_report_default(opts$generator_args$top_n, 20L),
      include_interactions = aq_shap_report_default(opts$generator_args$include_interactions, FALSE),
      report_args = opts$generator_args
    ),
    envir = Envir,
    quiet = opts$Quiet,
    clean = opts$Clean,
    output_options = list(self_contained = isTRUE(opts$SelfContained))
  )

  rendered_file <- normalizePath(rendered_file, winslash = "/", mustWork = FALSE)
  attr(rendered_file, "artifact_result") <- artifact_result
  if (isTRUE(opts$Open)) {
    utils::browseURL(rendered_file)
  }

  invisible(rendered_file)
}

# ============================================================
# Render Binary Classification SHAP Analysis Report from Artifacts
#
# RMarkdown template expected at:
#   inst/r-markdowns/Binary_Classification_SHAP_Analysis_Report.Rmd
#
# This function renders the AutoQuant-native standalone report path. It calls
# generate_binary_classification_shap_analysis_artifacts() when artifact_result
# is not supplied, but it does not compute SHAP values itself.
# ============================================================

#' Render Binary Classification SHAP Analysis Report
#'
#' Renders a standalone AutoQuant-native HTML report from Binary Classification
#' SHAP Analysis artifacts. If `artifact_result` is not supplied, this function
#' calls `generate_binary_classification_shap_analysis_artifacts()` first. Input
#' data must contain precomputed `Shap_` columns; this report function does not
#' compute SHAP values, call `predict()`, require a model object, or use a SHAP
#' backend package.
#'
#' @param data Optional data.table containing precomputed `Shap_` columns. Used
#'   only when `artifact_result` is NULL.
#' @param artifact_result Optional precomputed result returned by
#'   `generate_binary_classification_shap_analysis_artifacts()`.
#' @param OutputPath Directory where the rendered report should be written.
#' @param OutputFile Output HTML filename.
#' @param Title Report title.
#' @param Subtitle Optional report subtitle.
#' @param Theme Report theme label stored in render params. If `auto_plots_theme`
#'   is not supplied through `...`, this value is also passed to the artifact
#'   generator as `auto_plots_theme`.
#' @param Open If TRUE, open the rendered report in a browser.
#' @param Quiet Passed to `rmarkdown::render()`.
#' @param ... Analytical arguments passed to
#'   `generate_binary_classification_shap_analysis_artifacts()` when
#'   `artifact_result` is NULL, plus optional render controls `self_contained`,
#'   `RmdFile`, `Package`, `TemplatePath`, `Clean`, and `Envir`. Legacy
#'   lowercase render names such as `output_dir`, `output_file`, `title`,
#'   `subtitle`, `open`, and `quiet` are still accepted.
#'
#' @return Invisibly returns the rendered report path.
#'
#' @family Reports
#' @export
BinaryClassificationShapAnalysisReport <- function(
  artifact_result = NULL,
  data = NULL,
  OutputPath = getwd(),
  OutputFile = NULL,
  Title = "Binary Classification SHAP Analysis Report",
  Subtitle = NULL,
  Theme = "dark",
  Open = FALSE,
  Quiet = TRUE,
  ...
) {
  if (!requireNamespace("rmarkdown", quietly = TRUE)) {
    stop("Package 'rmarkdown' is required to render BinaryClassificationShapAnalysisReport().", call. = FALSE)
  }
  if (!requireNamespace("knitr", quietly = TRUE)) {
    stop("Package 'knitr' is required to render BinaryClassificationShapAnalysisReport().", call. = FALSE)
  }
  for (pkg in c("data.table", "htmltools", "reactable", "echarts4r", "AutoPlots")) {
    if (!requireNamespace(pkg, quietly = TRUE)) {
      stop(paste0("Package '", pkg, "' is required to render BinaryClassificationShapAnalysisReport()."), call. = FALSE)
    }
  }

  opts <- aq_shap_report_options(
    dots = list(...),
    OutputPath = OutputPath,
    OutputFile = OutputFile,
    Title = Title,
    Subtitle = Subtitle,
    Theme = Theme,
    Open = Open,
    Quiet = Quiet,
    default_output_file = "binary_classification_shap_analysis_report.html",
    default_rmd_file = "Binary_Classification_SHAP_Analysis_Report.Rmd"
  )

  artifact_result <- aq_prepare_binary_shap_report_artifact_result(
    data = data,
    artifact_result = artifact_result,
    generator_args = opts$generator_args
  )
  aq_validate_shap_report_artifact_result(artifact_result, "generate_binary_classification_shap_analysis_artifacts")

  output_dir <- normalizePath(opts$OutputPath, winslash = "/", mustWork = FALSE)
  dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)

  template_path <- aq_shap_report_template_path(opts$RmdFile, opts$Package, opts$TemplatePath)

  generated_at <- artifact_result$metadata$generated_at
  if (is.null(generated_at)) {
    generated_at <- Sys.time()
  }

  Envir <- opts$Envir
  if (is.null(Envir)) {
    Envir <- new.env(parent = .GlobalEnv)
  }
  assign("artifact_result", artifact_result, envir = Envir)
  assign("BinaryClassificationShapArtifacts", artifact_result, envir = Envir)

  rendered_file <- rmarkdown::render(
    input = template_path,
    output_file = opts$OutputFile,
    output_dir = output_dir,
    params = list(
      title = opts$Title,
      subtitle = opts$Subtitle,
      Theme = opts$Theme,
      generated_at = generated_at,
      artifact_result = artifact_result,
      artifact_sections = binary_shap_sections(),
      metadata = artifact_result$metadata,
      warnings = artifact_result$warnings,
      diagnostics = artifact_result$diagnostics,
      top_n = aq_shap_report_default(opts$generator_args$top_n, 20L),
      include_interactions = aq_shap_report_default(opts$generator_args$include_interactions, TRUE),
      report_args = opts$generator_args
    ),
    envir = Envir,
    quiet = opts$Quiet,
    clean = opts$Clean,
    output_options = list(self_contained = isTRUE(opts$SelfContained))
  )

  rendered_file <- normalizePath(rendered_file, winslash = "/", mustWork = FALSE)
  attr(rendered_file, "artifact_result") <- artifact_result
  if (isTRUE(opts$Open)) {
    utils::browseURL(rendered_file)
  }

  invisible(rendered_file)
}

#' QA SHAP Report Wrapper Contracts
#'
#' Validates that the SHAP report wrappers use the generator-first contract:
#' report functions accept concise rendering arguments, analytical arguments pass
#' through `...`, and supplied artifact results are reused without recomputing.
#'
#' @return A data.table of QA checks.
#'
#' @family QA
#' @export
qa_shap_report_wrapper_contracts <- function() {
  if (!requireNamespace("data.table", quietly = TRUE)) {
    stop("Package 'data.table' is required for qa_shap_report_wrapper_contracts().", call. = FALSE)
  }

  set.seed(42)
  n <- 80L
  reg_dt <- data.table::data.table(
    Target = stats::rnorm(n),
    Predict = stats::rnorm(n),
    Date = as.Date("2024-01-01") + sample(0:90, n, TRUE),
    Segment = sample(c("A", "B"), n, TRUE),
    FeatureA = stats::runif(n),
    FeatureB = stats::rnorm(n)
  )
  reg_dt[, Shap_FeatureA := 0.15 * FeatureA + stats::rnorm(.N, 0, 0.01)]
  reg_dt[, Shap_FeatureB := 0.05 * FeatureB + stats::rnorm(.N, 0, 0.01)]

  bin_dt <- data.table::copy(reg_dt)
  bin_dt[, Target := sample(c("Yes", "No"), .N, TRUE)]
  bin_dt[, Predict := stats::runif(.N)]
  bin_dt[, PredictedClass := ifelse(Predict >= 0.5, "Yes", "No")]

  reg_artifacts <- generate_regression_shap_analysis_artifacts(
    data = reg_dt,
    target_col = "Target",
    prediction_col = "Predict",
    DateVar = "Date",
    ByVars = "Segment",
    selected_features = c("FeatureA", "FeatureB"),
    top_n = 2L,
    include_plots = FALSE
  )
  bin_artifacts <- generate_binary_classification_shap_analysis_artifacts(
    data = bin_dt,
    target_col = "Target",
    prediction_col = "Predict",
    predicted_class_col = "PredictedClass",
    positive_class = "Yes",
    prediction_scale = "probability",
    threshold = 0.5,
    DateVar = "Date",
    ByVars = "Segment",
    selected_features = c("FeatureA", "FeatureB"),
    top_n = 2L,
    include_plots = FALSE
  )

  bad_dt <- data.table::data.table(NotShap = 1:3)
  reused_reg <- suppressWarnings(aq_prepare_regression_shap_report_artifact_result(
    data = bad_dt,
    artifact_result = reg_artifacts,
    generator_args = list(target_col = "Missing")
  ))
  reused_bin <- suppressWarnings(aq_prepare_binary_shap_report_artifact_result(
    data = bad_dt,
    artifact_result = bin_artifacts,
    generator_args = list(target_col = "Missing", positive_class = "Yes")
  ))

  direct_reg <- aq_prepare_regression_shap_report_artifact_result(
    data = reg_dt,
    artifact_result = NULL,
    generator_args = list(
      target_col = "Target",
      prediction_col = "Predict",
      DateVar = "Date",
      ByVars = "Segment",
      selected_features = c("FeatureA", "FeatureB"),
      top_n = 2L,
      include_plots = FALSE
    )
  )
  direct_bin <- aq_prepare_binary_shap_report_artifact_result(
    data = bin_dt,
    artifact_result = NULL,
    generator_args = list(
      target_col = "Target",
      prediction_col = "Predict",
      predicted_class_col = "PredictedClass",
      positive_class = "Yes",
      prediction_scale = "probability",
      threshold = 0.5,
      DateVar = "Date",
      ByVars = "Segment",
      selected_features = c("FeatureA", "FeatureB"),
      top_n = 2L,
      include_plots = FALSE
    )
  )

  reg_formals <- names(formals(RegressionShapAnalysisReport))
  bin_formals <- names(formals(BinaryClassificationShapAnalysisReport))
  expected_formals <- c("artifact_result", "data", "OutputPath", "OutputFile", "Title", "Subtitle", "Theme", "Open", "Quiet", "...")
  legacy_opts <- aq_shap_report_options(
    dots = list(output_dir = tempdir(), output_file = "legacy", title = "Legacy", quiet = FALSE, target_col = "Target"),
    OutputPath = getwd(),
    OutputFile = NULL,
    Title = "Default",
    Subtitle = NULL,
    Theme = "dark",
    Open = FALSE,
    Quiet = TRUE,
    default_output_file = "default.html",
    default_rmd_file = "Regression_SHAP_Analysis_Report.Rmd"
  )

  reg_template <- aq_shap_report_template_path("Regression_SHAP_Analysis_Report.Rmd", "AutoQuant", NULL)
  bin_template <- aq_shap_report_template_path("Binary_Classification_SHAP_Analysis_Report.Rmd", "AutoQuant", NULL)
  readme <- if (file.exists("README.md")) paste(readLines("README.md", warn = FALSE), collapse = "\n") else ""

  checks <- data.table::data.table(
    check = c(
      "regression_signature_simplified",
      "binary_signature_simplified",
      "regression_artifact_result_reused",
      "binary_artifact_result_reused",
      "regression_direct_data_dots_generated",
      "binary_direct_data_dots_generated",
      "legacy_render_aliases_removed_from_generator_args",
      "legacy_analytical_args_preserved",
      "regression_template_found",
      "binary_template_found",
      "readme_generator_first_example_present",
      "readme_convenience_example_present"
    ),
    status = c(
      if (identical(reg_formals, expected_formals)) "success" else "error",
      if (identical(bin_formals, expected_formals)) "success" else "error",
      if (identical(reused_reg, reg_artifacts)) "success" else "error",
      if (identical(reused_bin, bin_artifacts)) "success" else "error",
      if (is.list(direct_reg) && !is.null(direct_reg$artifacts)) "success" else "error",
      if (is.list(direct_bin) && !is.null(direct_bin$artifacts)) "success" else "error",
      if (!any(c("output_dir", "output_file", "title", "quiet") %in% names(legacy_opts$generator_args))) "success" else "error",
      if (identical(legacy_opts$generator_args$target_col, "Target")) "success" else "error",
      if (file.exists(reg_template)) "success" else "error",
      if (file.exists(bin_template)) "success" else "error",
      if (grepl("artifact_result = reg_artifacts", readme, fixed = TRUE) && grepl("artifact_result = binary_artifacts", readme, fixed = TRUE)) "success" else "error",
      if (grepl("Convenience wrapper", readme, fixed = TRUE)) "success" else "error"
    ),
    message = c(
      paste(reg_formals, collapse = ", "),
      paste(bin_formals, collapse = ", "),
      "Regression artifact_result path returns the supplied object.",
      "Binary artifact_result path returns the supplied object.",
      paste0("Regression artifacts: ", length(direct_reg$artifacts)),
      paste0("Binary artifacts: ", length(direct_bin$artifacts)),
      "Legacy render aliases are consumed by report options.",
      "Analytical arguments remain in generator_args.",
      reg_template,
      bin_template,
      "README includes artifact_result renderer examples.",
      "README includes data + ... convenience wrapper examples."
    )
  )

  checks
}

#' QA Modern Report API Contracts
#'
#' Validates the generator-first/report-renderer contract for modern AutoQuant
#' report wrappers. Generators own analytical parameters; report functions own
#' rendering parameters and accept analytical arguments only through `...`.
#'
#' @return A data.table of QA checks.
#'
#' @family QA
#' @export
qa_report_api_contracts <- function() {
  if (!requireNamespace("data.table", quietly = TRUE)) {
    stop("Package 'data.table' is required for qa_report_api_contracts().", call. = FALSE)
  }

  expected_formals <- c("artifact_result", "data", "OutputPath", "OutputFile", "Title", "Subtitle", "Theme", "Open", "Quiet", "...")
  report_functions <- list(
    EDAReport = EDAReport,
    TargetAnalysisReport = TargetAnalysisReport,
    RegressionModelInsightsReport = RegressionModelInsightsReport,
    BinaryClassificationModelInsightsReport = BinaryClassificationModelInsightsReport,
    RegressionShapAnalysisReport = RegressionShapAnalysisReport,
    BinaryClassificationShapAnalysisReport = BinaryClassificationShapAnalysisReport
  )
  signature_checks <- data.table::rbindlist(lapply(names(report_functions), function(fn_name) {
    current <- names(formals(report_functions[[fn_name]]))
    data.table::data.table(
      check = paste0(fn_name, "_signature"),
      status = if (identical(current, expected_formals)) "success" else "error",
      message = paste(current, collapse = ", ")
    )
  }))

  set.seed(101)
  n <- 80L
  dt <- data.table::data.table(
    Target = stats::rnorm(n),
    Predict = stats::rnorm(n),
    TargetBinary = sample(c("Yes", "No"), n, TRUE),
    PredictedClass = sample(c("Yes", "No"), n, TRUE),
    Prob = stats::runif(n),
    Date = as.Date("2024-01-01") + sample(0:90, n, TRUE),
    Segment = sample(c("A", "B"), n, TRUE),
    FeatureA = stats::runif(n),
    FeatureB = stats::rnorm(n)
  )
  dt[, Shap_FeatureA := 0.15 * FeatureA + stats::rnorm(.N, 0, 0.01)]
  dt[, Shap_FeatureB := 0.05 * FeatureB + stats::rnorm(.N, 0, 0.01)]

  eda_artifacts <- generate_eda_artifacts(
    data = dt,
    DataName = "Report API QA",
    UnivariateVars = c("FeatureA", "FeatureB", "Segment"),
    CorrVars = c("FeatureA", "FeatureB", "Predict"),
    TrendVars = NULL,
    Theme = "dark"
  )
  target_artifacts <- generate_model_assessment_artifacts(
    data = dt,
    DataName = "Report API QA",
    TargetVar = "TargetBinary",
    TrendDateVar = NULL,
    TrendGroupVar = NULL,
    Theme = "dark",
    RunGAMDiagnostics = FALSE
  )
  reg_mi_artifacts <- generate_regression_model_insights_artifacts(
    TestData = dt,
    TargetColumnName = "Target",
    PredictionColumnName = "Predict",
    FeatureColumnNames = c("FeatureA", "FeatureB", "Segment"),
    GenerateCalibrationPDP = FALSE,
    GenerateUpliftPDP = FALSE,
    GenerateStratifiedEffects = FALSE,
    DetectSimpsonsParadox = FALSE,
    Theme = "dark"
  )
  bin_mi_artifacts <- generate_binary_classification_model_insights_artifacts(
    data = dt,
    target_col = "TargetBinary",
    prediction_col = "Prob",
    predicted_class_col = "PredictedClass",
    positive_class = "Yes",
    feature_cols = c("FeatureA", "FeatureB", "Segment"),
    Theme = "dark"
  )
  reg_shap_artifacts <- generate_regression_shap_analysis_artifacts(
    data = dt,
    target_col = "Target",
    prediction_col = "Predict",
    selected_features = c("FeatureA", "FeatureB"),
    top_n = 2L,
    include_plots = FALSE
  )
  bin_shap_artifacts <- generate_binary_classification_shap_analysis_artifacts(
    data = dt,
    target_col = "TargetBinary",
    prediction_col = "Prob",
    predicted_class_col = "PredictedClass",
    positive_class = "Yes",
    prediction_scale = "probability",
    selected_features = c("FeatureA", "FeatureB"),
    top_n = 2L,
    include_plots = FALSE
  )

  opts <- aq_report_render_options(
    dots = list(output_file = "legacy", title = "Legacy", target_col = "Target"),
    OutputPath = getwd(),
    OutputFile = NULL,
    Title = "Default",
    Subtitle = NULL,
    Theme = "dark",
    Open = FALSE,
    Quiet = TRUE,
    default_output_file = "default.html",
    default_rmd_file = "EDA_Report.Rmd"
  )
  template_files <- c(
    aq_report_template_path("EDA_Report.Rmd", "AutoQuant", NULL),
    aq_report_template_path("Target_Analysis_Report.Rmd", "AutoQuant", NULL),
    aq_report_template_path("Regression_ModelInsights_Artifact_Renderer.Rmd", "AutoQuant", NULL),
    aq_report_template_path("Binary_Classification_ModelInsights_Artifact_Renderer.Rmd", "AutoQuant", NULL),
    aq_report_template_path("Regression_SHAP_Analysis_Report.Rmd", "AutoQuant", NULL),
    aq_report_template_path("Binary_Classification_SHAP_Analysis_Report.Rmd", "AutoQuant", NULL)
  )

  render_available <- requireNamespace("rmarkdown", quietly = TRUE) &&
    requireNamespace("prettydoc", quietly = TRUE) &&
    rmarkdown::pandoc_available()
  render_status <- "success"
  render_message <- "Pandoc/prettydoc unavailable; validated wrapper signatures, generators, and templates only."
  if (render_available) {
    render_dir <- file.path(tempdir(), paste0("autoquant_report_api_qa_", as.integer(Sys.time())))
    dir.create(render_dir, recursive = TRUE, showWarnings = FALSE)
    render_attempt <- tryCatch({
      EDAReport(
        artifact_result = eda_artifacts,
        OutputPath = render_dir,
        OutputFile = "eda_report_api_qa.html",
        Quiet = TRUE,
        SelfContained = FALSE
      )
    }, error = function(e) e)
    render_status <- if (inherits(render_attempt, "error")) "error" else "success"
    render_message <- if (inherits(render_attempt, "error")) conditionMessage(render_attempt) else as.character(render_attempt)
  }

  contract_checks <- data.table::data.table(
    check = c(
      "eda_generator_output",
      "target_generator_output",
      "regression_model_insights_generator_output",
      "binary_model_insights_generator_output",
      "regression_shap_generator_output",
      "binary_shap_generator_output",
      "render_aliases_removed_from_generator_args",
      "analytical_args_pass_through",
      "templates_found",
      "artifact_result_render_path"
    ),
    status = c(
      if (!is.null(eda_artifacts$tables) || !is.null(eda_artifacts$plots)) "success" else "error",
      if (!is.null(target_artifacts$tables) || !is.null(target_artifacts$plots)) "success" else "error",
      if (!is.null(reg_mi_artifacts$tables) || !is.null(reg_mi_artifacts$plots)) "success" else "error",
      if (!is.null(bin_mi_artifacts$artifacts)) "success" else "error",
      if (!is.null(reg_shap_artifacts$artifacts)) "success" else "error",
      if (!is.null(bin_shap_artifacts$artifacts)) "success" else "error",
      if (!any(c("output_file", "title") %in% names(opts$generator_args))) "success" else "error",
      if (identical(opts$generator_args$target_col, "Target")) "success" else "error",
      if (all(file.exists(template_files))) "success" else "error",
      render_status
    ),
    message = c(
      paste0("EDA tables: ", length(eda_artifacts$tables), "; plots: ", length(eda_artifacts$plots)),
      paste0("Target/readiness tables: ", length(target_artifacts$tables), "; plots: ", length(target_artifacts$plots)),
      paste0("Regression MI tables: ", length(reg_mi_artifacts$tables)),
      paste0("Binary MI artifacts: ", length(bin_mi_artifacts$artifacts)),
      paste0("Regression SHAP artifacts: ", length(reg_shap_artifacts$artifacts)),
      paste0("Binary SHAP artifacts: ", length(bin_shap_artifacts$artifacts)),
      "Render aliases are consumed by report options.",
      "Generator arguments remain in `...`.",
      paste(template_files, collapse = " | "),
      render_message
    )
  )

  data.table::rbindlist(list(signature_checks, contract_checks), use.names = TRUE, fill = TRUE)
}
