# AutoQuant is a package for quickly creating high quality visualizations under a common and easy api.
# Copyright (C) <year>  <name of author>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

#' @title Run_ModelInsightsReport
#'
#' @description Run_ModelInsightsReport is an Rmarkdown report for viewing the model insights generated by AutoQuant supervised learning functions
#'
#' @author Adrian Antico
#' @family Reports
#'
#' @param TrainDataInclude Default FALSE. If FALSE, no derived visuals or metrics for TrainData
#' @param FeatureColumnNames NULL
#' @param SampleSize Default 100000
#' @param ModelObject Output from a AutoQuant supervised learning function
#' @param ModelID ModelID used in the AutoQuant supervised learning function
#' @param SourcePath Path to directory with DataQuant Model Output
#' @param OutputPath Path to directory where the html will be saved
#'
#' @noRd
Run_ModelInsightsReport <- function(TrainDataInclude = FALSE,
                                    FeatureColumnNames = NULL,
                                    SampleSize = 100000,
                                    ModelObject = NULL,
                                    ModelID = NULL,
                                    SourcePath = NULL,
                                    OutputPath = NULL) {

  # Directory reference
  appDir <- system.file("r-markdowns", package = "AutoQuant")

  # @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
  # Globalize the parameters
  # @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

  # ModelObject
  ModelObject <<- ModelObject

  # Finalize Passthrough
  if(!is.null(ModelObject)) {

    # DataSets
    ModelObject[['TestData']] <- ModelObject[['TestData']][order(runif(.N))][seq_len(min(.N, SampleSize))]
    if(TrainDataInclude) {
      ModelObject[['TrainData']] <- ModelObject[['TrainData']][order(runif(.N))][seq_len(min(.N, SampleSize))]
    } else {
      ModelObject[['TrainData']] <- NULL
    }

    # Meta info
    TargetType <- ModelObject[["ArgsList"]][["TargetType"]]
    if(TargetType == "Binary Classification") TargetType <- "classification"
    TargetColumnName <- ModelObject[['ArgsList']][['TargetColumnName']]
    PredictionColumnName <- ModelObject[["ArgsList"]][["PredictionColumnName"]]
    TargetLevels <- ModelObject[["ArgsList"]][["TargetLevels"]]
    Algo <- tolower(ModelObject[["ArgsList"]][["Algo"]])
    if(is.null(FeatureColumnNames)) {
      FeatureColumnNames <- ModelObject[['ColNames']][[1L]]
    }
    ArgsList <- ModelObject[['ArgsList']]

  } else {
    return(NULL)
  }

  if(length(ModelObject[['TestData']]) == 0L && length(ModelObject[['TrainData']]) == 0L) return(NULL)

  # Metadata args
  TargetType <- TargetType
  TargetLevels <- TargetLevels
  ModelID <- ModelID
  Algo <- Algo
  SourcePath <- SourcePath
  OutputPath <- OutputPath
  OutputPathName <- file.path(OutputPath, paste0('MLReport-', ModelID, '-', TargetType, '.html'))

  # @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
  # Select Rmarkdown Report and Run it
  # @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

  # Regression Markdown
  if(tolower(TargetType) == 'regression') {
    rmarkdown::render(
      input = file.path(appDir, 'Regression_ModelInsights.Rmd'),
      output_file = OutputPathName)
  }

  # Classification Markdown
  if(tolower(TargetType) == 'classification') {
    rmarkdown::render(
      input = file.path(appDir, 'Classification_ModelInsights.Rmd'),
      output_file = OutputPathName)
  }

  # MultiClass Markdown
  if(tolower(TargetType) == 'multiclass') {
    rmarkdown::render(
      input = file.path(appDir, 'MultiClass_ModelInsights.Rmd'),
      output_file = OutputPathName)
  }
}

#' @title ModelInsightsReport
#'
#' @description
#' Legacy RMarkdown report for model insights generated by AutoQuant supervised
#' learning functions. Prefer the artifact-first report functions:
#' `RegressionModelInsightsReport()` for regression and
#' `BinaryClassificationModelInsightsReport()` for binary classification.
#'
#' @author Adrian Antico
#' @family Reports
#'
#' @param TrainDataInclude Default FALSE. If FALSE, no derived visuals or metrics for TrainData
#' @param FeatureColumnNames NULL. Feature column names as character vector.
#' @param SampleSize Default 100000
#' @param ModelObject Returned output from regression, classificaiton, and multiclass Remix Auto_() models. Currenly supports CatBoost, XGBoost, and LightGBM models
#' @param ModelID ModelID used in the AutoQuant supervised learning function
#' @param SourcePath Path to directory with AutoQuant Model Output
#' @param OutputPath Path to directory where the html will be saved
#' @param GlobalVars ls() don't use
#' @param KeepOutput NULL A list of output names to select. Pass in as a character vector. E.g. c('Test_VariableImportance', 'Train_VariableImportance')
#'
#' @export
ModelInsightsReport <- function(TrainDataInclude = FALSE,
                                FeatureColumnNames = NULL,
                                SampleSize = 100000,
                                ModelObject = NULL,
                                ModelID = 'ModelTest',
                                SourcePath = NULL,
                                OutputPath = NULL,
                                KeepOutput = NULL,
                                GlobalVars = ls()) {

  # Run Function
  Run_ModelInsightsReport(
    TrainDataInclude = TrainDataInclude,
    FeatureColumnNames = FeatureColumnNames,
    SampleSize = SampleSize,
    ModelObject = ModelObject,
    ModelID = ModelID,
    SourcePath = SourcePath,
    OutputPath = OutputPath)

  # Remove objects
  GlobalVarsNew <- ls()
  rm(list = c(setdiff(GlobalVarsNew, c(GlobalVars, KeepOutput))))
}

#' @title Exploratory Data Analysis Report
#'
#' @description
#' Renders an HTML exploratory data analysis report from a pre-generated EDA
#' artifact object created by `generate_eda_artifacts()`.
#'
#' @author Adrian Antico
#' @family Reports
#'
#' @param artifacts Output object returned by `generate_eda_artifacts()`.
#' @param OutputPath Directory where the rendered HTML report should be saved.
#'   If `NULL`, the current working directory is used.
#' @param DataName Optional report/data name. If `NULL`, attempts to use
#'   `artifacts$metadata$DataName`, then falls back to `"EDA Data"`.
#' @param Theme Character value passed through to the RMarkdown report.
#' @param OutputFile Optional full output file path. If `NULL`, a file name is
#'   generated as `"EDAReport-{DataName}.html"` inside `OutputPath`.
#'
#' @return Invisibly returns the rendered HTML file path.
#'
#' @details
#' This function does not compute EDA artifacts. It only renders the report from
#' artifacts that were already generated. This separates artifact generation from
#' report rendering, allowing the same artifact object to be reused for
#' RMarkdown, Shiny, PNG export, HTML export, or LLM/API workflows.
#'
#' Typical usage:
#'
#' \preformatted{
#' artifacts <- generate_eda_artifacts(
#'   data = dt,
#'   DataName = "EDA Data",
#'   UnivariateVars = UnivariateVars,
#'   CorrVars = CorrVars,
#'   TrendVars = TrendVars,
#'   TrendDateVar = "event_date",
#'   TrendGroupVar = "channel",
#'   Theme = "dark"
#' )
#'
#' EDAReport(
#'   artifacts = artifacts,
#'   OutputPath = "reports"
#' )
#' }
#'
#' @export
EDAReport <- function(
    artifacts,
    OutputPath = NULL,
    DataName = NULL,
    Theme = "dark",
    OutputFile = NULL
) {

  if (missing(artifacts) || is.null(artifacts)) {
    stop(
      "`artifacts` must be supplied. Use `generate_eda_artifacts()` first.",
      call. = FALSE
    )
  }

  appDir <- system.file("r-markdowns", package = "AutoQuant")

  if (!nzchar(appDir)) {
    stop(
      "Could not find the AutoQuant RMarkdown directory: inst/r-markdowns.",
      call. = FALSE
    )
  }

  rmd_file <- file.path(appDir, "EDA_Report.Rmd")

  if (!file.exists(rmd_file)) {
    stop(
      "Could not find the EDA report RMarkdown file: ",
      rmd_file,
      call. = FALSE
    )
  }

  if (is.null(OutputPath)) {
    OutputPath <- getwd()
  }

  OutputPath <- normalizePath(
    OutputPath,
    winslash = "/",
    mustWork = FALSE
  )

  if (!dir.exists(OutputPath)) {
    dir.create(OutputPath, recursive = TRUE, showWarnings = FALSE)
  }

  if (is.null(DataName)) {
    DataName <- tryCatch(
      artifacts$metadata$DataName,
      error = function(e) NULL
    )
  }

  if (
    is.null(DataName) ||
    length(DataName) == 0L ||
    is.na(DataName[1L]) ||
    !nzchar(as.character(DataName[1L]))
  ) {
    DataName <- "EDA Data"
  }

  DataName <- as.character(DataName[1L])

  safe_data_name <- gsub("[^A-Za-z0-9_-]+", "_", DataName)
  safe_data_name <- gsub("_+", "_", safe_data_name)
  safe_data_name <- gsub("^_|_$", "", safe_data_name)

  if (!nzchar(safe_data_name)) {
    safe_data_name <- "EDA_Data"
  }

  if (is.null(OutputFile)) {

    OutputFile <- file.path(
      OutputPath,
      paste0("EDAReport-", safe_data_name, ".html")
    )

  } else {

    OutputFile <- path.expand(OutputFile)

    output_file_dir <- dirname(OutputFile)

    if (!dir.exists(output_file_dir)) {
      dir.create(output_file_dir, recursive = TRUE, showWarnings = FALSE)
    }

    OutputFile <- normalizePath(
      OutputFile,
      winslash = "/",
      mustWork = FALSE
    )
  }

  rmarkdown::render(
    input = rmd_file,
    output_file = OutputFile,
    params = list(
      artifacts = artifacts,
      DataName = DataName,
      Theme = Theme
    ),
    envir = new.env(parent = globalenv())
  )

  invisible(OutputFile)
}

#' @title Target Analysis Report
#'
#' @description
#' Renders an HTML target analysis / model readiness report from a pre-generated
#' artifact object created by `generate_model_assessment_artifacts()`.
#'
#' @author Adrian Antico
#' @family Reports
#'
#' @param artifacts Output object returned by `generate_model_assessment_artifacts()`.
#' @param OutputPath Directory where the rendered HTML report should be saved.
#'   If `NULL`, the current working directory is used.
#' @param DataName Optional report/data name. If `NULL`, attempts to use
#'   `artifacts$metadata$DataName`, then falls back to `"Modeling Data"`.
#' @param Theme Character value passed through to the RMarkdown report.
#' @param OutputFile Optional full output file path. If `NULL`, a file name is
#'   generated as `"TargetAnalysis-{DataName}.html"` inside `OutputPath`.
#'
#' @return Invisibly returns the rendered HTML file path.
#'
#' @details
#' This function does not compute target analysis artifacts. It only renders the
#' report from artifacts that were already generated. This separates evidence
#' generation from report rendering, allowing the same artifact object to be
#' reused for RMarkdown, Shiny, static exports, or LLM/API workflows.
#'
#' Typical usage:
#'
#' \preformatted{
#' artifacts <- generate_model_assessment_artifacts(
#'   data = dt,
#'   DataName = "Modeling Data",
#'   TargetVar = "conversions",
#'   TrendDateVar = "event_date",
#'   TrendGroupVar = c("channel", "market"),
#'   Theme = "dark"
#' )
#'
#' TargetAnalysisReport(
#'   artifacts = artifacts,
#'   OutputPath = "reports"
#' )
#' }
#'
#' @export
TargetAnalysisReport <- function(
    artifacts,
    OutputPath = NULL,
    DataName = NULL,
    Theme = "dark",
    OutputFile = NULL
) {

  if (missing(artifacts) || is.null(artifacts)) {
    stop(
      "`artifacts` must be supplied. Use `generate_model_assessment_artifacts()` first.",
      call. = FALSE
    )
  }

  appDir <- system.file("r-markdowns", package = "AutoQuant")

  if (!nzchar(appDir)) {
    stop(
      "Could not find the AutoQuant RMarkdown directory: inst/r-markdowns.",
      call. = FALSE
    )
  }

  rmd_file <- file.path(appDir, "Target_Analysis_Report.Rmd")

  if (!file.exists(rmd_file)) {
    stop(
      "Could not find the Target Analysis report RMarkdown file: ",
      rmd_file,
      call. = FALSE
    )
  }

  if (is.null(OutputPath)) {
    OutputPath <- getwd()
  }

  OutputPath <- normalizePath(
    OutputPath,
    winslash = "/",
    mustWork = FALSE
  )

  if (!dir.exists(OutputPath)) {
    dir.create(OutputPath, recursive = TRUE, showWarnings = FALSE)
  }

  if (is.null(DataName)) {
    DataName <- tryCatch(
      artifacts$metadata$DataName,
      error = function(e) NULL
    )
  }

  if (
    is.null(DataName) ||
    length(DataName) == 0L ||
    is.na(DataName[1L]) ||
    !nzchar(as.character(DataName[1L]))
  ) {
    DataName <- "Modeling Data"
  }

  DataName <- as.character(DataName[1L])

  safe_data_name <- gsub("[^A-Za-z0-9_-]+", "_", DataName)
  safe_data_name <- gsub("_+", "_", safe_data_name)
  safe_data_name <- gsub("^_|_$", "", safe_data_name)

  if (!nzchar(safe_data_name)) {
    safe_data_name <- "Modeling_Data"
  }

  if (is.null(OutputFile)) {

    OutputFile <- file.path(
      OutputPath,
      paste0("TargetAnalysis-", safe_data_name, ".html")
    )

  } else {

    OutputFile <- path.expand(OutputFile)

    output_file_dir <- dirname(OutputFile)

    if (!dir.exists(output_file_dir)) {
      dir.create(output_file_dir, recursive = TRUE, showWarnings = FALSE)
    }

    OutputFile <- normalizePath(
      OutputFile,
      winslash = "/",
      mustWork = FALSE
    )
  }

  rmarkdown::render(
    input = rmd_file,
    output_file = OutputFile,
    params = list(
      artifacts = artifacts,
      DataName = DataName,
      Theme = Theme
    ),
    envir = new.env(parent = globalenv())
  )

  invisible(OutputFile)
}

# ============================================================
# Render Regression Model Insights Report from Artifacts
#
# RMarkdown template expected at:
#   inst/r-markdowns/Regression_ModelInsights_Artifact_Renderer.Rmd
#
# This function intentionally does only one thing:
#   take a precomputed artifacts object and render the report.
# ============================================================

#' Render Regression Model Insights Report
#'
#' Takes a precomputed regression model-insights artifact object and renders
#' the artifact-based RMarkdown report.
#'
#' @param artifacts Artifact object returned by
#'   `generate_regression_model_insights_artifacts()`.
#' @param OutputPath Directory where the rendered HTML report should be written.
#' @param OutputFile Output HTML filename.
#' @param RmdFile RMarkdown filename located in `inst/r-markdowns`.
#' @param Package Package name used to locate installed RMarkdown files.
#' @param TemplatePath Optional explicit path to the RMarkdown file. If supplied,
#'   this takes precedence over the package/system.file lookup.
#' @param Quiet Passed to `rmarkdown::render()`.
#' @param Clean Passed to `rmarkdown::render()`.
#' @param Envir Optional render environment. If NULL, a clean child environment
#'   of `.GlobalEnv` is created.
#' @param SelfContained Passed to `rmarkdown::render()` through output_options.
#'
#' @return Invisibly returns the rendered report path.
#'
#' @family Reports
#' @export
RegressionModelInsightsReport <- function(
    artifacts,
    OutputPath = getwd(),
    OutputFile = "Regression_ModelInsights_Report.html",
    RmdFile = "Regression_ModelInsights_Artifact_Renderer.Rmd",
    Package = "AutoQuant",
    TemplatePath = NULL,
    Quiet = FALSE,
    Clean = TRUE,
    Envir = NULL,
    SelfContained = TRUE
) {

  if (missing(artifacts) || is.null(artifacts)) {
    stop("`artifacts` must be supplied.", call. = FALSE)
  }

  if (!requireNamespace("rmarkdown", quietly = TRUE)) {
    stop("Package 'rmarkdown' is required.", call. = FALSE)
  }

  if (!requireNamespace("data.table", quietly = TRUE)) {
    stop("Package 'data.table' is required.", call. = FALSE)
  }

  if (!requireNamespace("htmltools", quietly = TRUE)) {
    stop("Package 'htmltools' is required.", call. = FALSE)
  }

  if (!requireNamespace("reactable", quietly = TRUE)) {
    stop("Package 'reactable' is required.", call. = FALSE)
  }

  if (!requireNamespace("echarts4r", quietly = TRUE)) {
    stop("Package 'echarts4r' is required.", call. = FALSE)
  }

  if (!requireNamespace("AutoPlots", quietly = TRUE)) {
    stop("Package 'AutoPlots' is required.", call. = FALSE)
  }

  OutputPath <- normalizePath(OutputPath, winslash = "/", mustWork = FALSE)
  dir.create(OutputPath, recursive = TRUE, showWarnings = FALSE)

  if (!is.null(TemplatePath) && nzchar(TemplatePath)) {

    TemplatePath <- normalizePath(TemplatePath, winslash = "/", mustWork = FALSE)

  } else {

    TemplatePath <- system.file(
      "r-markdowns",
      RmdFile,
      package = Package
    )

    # Development fallback before package installation.
    if (!nzchar(TemplatePath) || !file.exists(TemplatePath)) {
      TemplatePath <- file.path(
        getwd(),
        "inst",
        "r-markdowns",
        RmdFile
      )
      TemplatePath <- normalizePath(TemplatePath, winslash = "/", mustWork = FALSE)
    }

    # Working-directory fallback for ad hoc testing.
    if (!file.exists(TemplatePath)) {
      TemplatePath <- file.path(getwd(), RmdFile)
      TemplatePath <- normalizePath(TemplatePath, winslash = "/", mustWork = FALSE)
    }
  }

  if (!file.exists(TemplatePath)) {
    stop(
      paste0(
        "RMarkdown template not found. Expected one of:\n",
        "1. ", file.path("inst", "r-markdowns", RmdFile), "\n",
        "2. system.file('r-markdowns', '", RmdFile, "', package = '", Package, "')\n",
        "3. Explicit `TemplatePath`."
      ),
      call. = FALSE
    )
  }

  if (is.null(Envir)) {
    Envir <- new.env(parent = .GlobalEnv)
  }

  # Expose both names because the Rmd supports either lookup pattern.
  assign("artifacts", artifacts, envir = Envir)
  assign("ModelInsightsArtifacts", artifacts, envir = Envir)

  RenderedFile <- rmarkdown::render(
    input = TemplatePath,
    output_file = OutputFile,
    output_dir = OutputPath,
    params = list(
      artifacts = artifacts
    ),
    envir = Envir,
    quiet = Quiet,
    clean = Clean,
    output_options = list(
      self_contained = isTRUE(SelfContained)
    )
  )

  RenderedFile <- normalizePath(RenderedFile, winslash = "/", mustWork = FALSE)

  invisible(RenderedFile)
}

# ============================================================
# Render Binary Classification Model Insights Report from Artifacts
#
# RMarkdown template expected at:
#   inst/r-markdowns/Binary_Classification_ModelInsights_Artifact_Renderer.Rmd
# ============================================================

#' Render Binary Classification Model Insights Report
#'
#' Takes a precomputed binary classification model-insights artifact object, or
#' generates one from scored data, and renders the artifact-based standalone
#' HTML report.
#'
#' @param artifacts Artifact object returned by
#'   `generate_binary_classification_model_insights_artifacts()`. If NULL,
#'   scored `data` and target/prediction columns are passed to the generator.
#' @param data Optional scored/model-output data used when `artifacts` is NULL.
#' @param target_col,prediction_col,predicted_class_col Column names passed to
#'   `generate_binary_classification_model_insights_artifacts()`.
#' @param positive_class Positive target class.
#' @param feature_cols Optional feature columns used for feature diagnostics.
#' @param model_name,data_name Optional labels stored in report metadata.
#' @param DateVar Optional date column used for time diagnostics.
#' @param date_aggregation Time aggregation for `DateVar`.
#' @param ByVars Optional segment columns used for segment diagnostics.
#' @param threshold Default operating threshold.
#' @param optimize_metric Threshold optimization metric.
#' @param OutputPath Directory where the rendered HTML report should be written.
#' @param OutputFile Output HTML filename.
#' @param RmdFile RMarkdown filename located in `inst/r-markdowns`.
#' @param Package Package name used to locate installed RMarkdown files.
#' @param TemplatePath Optional explicit path to the RMarkdown file. If supplied,
#'   this takes precedence over the package/system.file lookup.
#' @param Quiet Passed to `rmarkdown::render()`.
#' @param Clean Passed to `rmarkdown::render()`.
#' @param Envir Optional render environment. If NULL, a clean child environment
#'   of `.GlobalEnv` is created.
#' @param SelfContained Passed to `rmarkdown::render()` through output_options.
#' @param ... Additional arguments passed to
#'   `generate_binary_classification_model_insights_artifacts()` when
#'   `artifacts` is NULL.
#'
#' @return Invisibly returns the rendered report path.
#'
#' @family Reports
#' @export
BinaryClassificationModelInsightsReport <- function(
  artifacts = NULL,
  data = NULL,
  target_col = NULL,
  prediction_col = NULL,
  predicted_class_col = NULL,
  positive_class = NULL,
  feature_cols = NULL,
  model_name = NULL,
  data_name = NULL,
  DateVar = NULL,
  date_aggregation = "month",
  ByVars = character(),
  threshold = 0.5,
  optimize_metric = "Utility",
  OutputPath = getwd(),
  OutputFile = "Binary_Classification_ModelInsights_Report.html",
  RmdFile = "Binary_Classification_ModelInsights_Artifact_Renderer.Rmd",
  Package = "AutoQuant",
  TemplatePath = NULL,
  Quiet = FALSE,
  Clean = TRUE,
  Envir = NULL,
  SelfContained = TRUE,
  ...
) {
  if (is.null(artifacts)) {
    if (is.null(data)) {
      stop("Supply `artifacts`, or supply scored `data` plus target/prediction columns.", call. = FALSE)
    }
    artifacts <- generate_binary_classification_model_insights_artifacts(
      data = data,
      target_col = target_col,
      prediction_col = prediction_col,
      predicted_class_col = predicted_class_col,
      positive_class = positive_class,
      feature_cols = feature_cols,
      model_name = model_name,
      data_name = data_name,
      DateVar = DateVar,
      date_aggregation = date_aggregation,
      ByVars = ByVars,
      Threshold = threshold,
      OptimizeMetric = optimize_metric,
      ...
    )
  }
  if (!is.list(artifacts) || is.null(artifacts$artifacts) || is.null(artifacts$metadata)) {
    stop("`artifacts` must be an object returned by generate_binary_classification_model_insights_artifacts().", call. = FALSE)
  }
  for (pkg in c("rmarkdown", "data.table", "htmltools", "reactable", "AutoPlots")) {
    if (!requireNamespace(pkg, quietly = TRUE)) {
      stop(paste0("Package '", pkg, "' is required."), call. = FALSE)
    }
  }

  OutputPath <- normalizePath(OutputPath, winslash = "/", mustWork = FALSE)
  dir.create(OutputPath, recursive = TRUE, showWarnings = FALSE)

  if (!is.null(TemplatePath) && nzchar(TemplatePath)) {
    TemplatePath <- normalizePath(TemplatePath, winslash = "/", mustWork = FALSE)
  } else {
    TemplatePath <- system.file("r-markdowns", RmdFile, package = Package)
    if (!nzchar(TemplatePath) || !file.exists(TemplatePath)) {
      TemplatePath <- normalizePath(file.path(getwd(), "inst", "r-markdowns", RmdFile), winslash = "/", mustWork = FALSE)
    }
    if (!file.exists(TemplatePath)) {
      TemplatePath <- normalizePath(file.path(getwd(), RmdFile), winslash = "/", mustWork = FALSE)
    }
  }

  if (!file.exists(TemplatePath)) {
    stop(
      paste0(
        "RMarkdown template not found. Expected one of:\n",
        "1. ", file.path("inst", "r-markdowns", RmdFile), "\n",
        "2. system.file('r-markdowns', '", RmdFile, "', package = '", Package, "')\n",
        "3. Explicit `TemplatePath`."
      ),
      call. = FALSE
    )
  }

  if (is.null(Envir)) {
    Envir <- new.env(parent = .GlobalEnv)
  }

  assign("artifacts", artifacts, envir = Envir)
  assign("BinaryClassificationModelInsightsArtifacts", artifacts, envir = Envir)

  RenderedFile <- rmarkdown::render(
    input = TemplatePath,
    output_file = OutputFile,
    output_dir = OutputPath,
    params = list(artifacts = artifacts),
    envir = Envir,
    quiet = Quiet,
    clean = Clean,
    output_options = list(self_contained = isTRUE(SelfContained))
  )

  RenderedFile <- normalizePath(RenderedFile, winslash = "/", mustWork = FALSE)
  invisible(RenderedFile)
}

# ============================================================
# Render Regression SHAP Analysis Report from Artifacts
#
# RMarkdown template expected at:
#   inst/r-markdowns/Regression_SHAP_Analysis_Report.Rmd
#
# This function renders the AutoQuant-native standalone report path. It calls
# generate_regression_shap_analysis_artifacts() when artifact_result is not
# supplied, but it does not compute SHAP values itself.
# ============================================================

aq_shap_report_pop_arg <- function(args, names, default = NULL) {
  for (nm in names) {
    if (nm %in% names(args)) {
      return(args[[nm]])
    }
  }
  default
}

aq_shap_report_drop_args <- function(args, names) {
  args[setdiff(names(args), names)]
}

aq_shap_report_default <- function(value, default) {
  if (is.null(value)) default else value
}

aq_shap_report_options <- function(
  dots,
  OutputPath,
  OutputFile,
  Title,
  Subtitle,
  Theme,
  Open,
  Quiet,
  default_output_file,
  default_rmd_file
) {
  render_names <- c(
    "OutputPath", "output_path", "output_dir",
    "OutputFile", "output_file",
    "Title", "title",
    "Subtitle", "subtitle",
    "Theme", "theme",
    "Open", "open",
    "Quiet", "quiet",
    "SelfContained", "self_contained",
    "RmdFile", "Package", "TemplatePath", "Clean", "Envir"
  )

  output_path <- aq_shap_report_pop_arg(dots, c("OutputPath", "output_path", "output_dir"), OutputPath)
  output_file <- aq_shap_report_pop_arg(dots, c("OutputFile", "output_file"), OutputFile)
  title <- aq_shap_report_pop_arg(dots, c("Title", "title"), Title)
  subtitle <- aq_shap_report_pop_arg(dots, c("Subtitle", "subtitle"), Subtitle)
  theme <- aq_shap_report_pop_arg(dots, c("Theme", "theme"), Theme)
  open <- aq_shap_report_pop_arg(dots, c("Open", "open"), Open)
  quiet <- aq_shap_report_pop_arg(dots, c("Quiet", "quiet"), Quiet)
  self_contained <- aq_shap_report_pop_arg(dots, c("SelfContained", "self_contained"), TRUE)
  rmd_file <- aq_shap_report_pop_arg(dots, "RmdFile", default_rmd_file)
  package <- aq_shap_report_pop_arg(dots, "Package", "AutoQuant")
  template_path <- aq_shap_report_pop_arg(dots, "TemplatePath", NULL)
  clean <- aq_shap_report_pop_arg(dots, "Clean", TRUE)
  envir <- aq_shap_report_pop_arg(dots, "Envir", NULL)
  generator_args <- aq_shap_report_drop_args(dots, render_names)

  if (is.null(output_file) || !nzchar(output_file)) {
    output_file <- default_output_file
  }
  if (!grepl("\\.html?$", output_file, ignore.case = TRUE)) {
    output_file <- paste0(output_file, ".html")
  }

  if (!("auto_plots_theme" %in% names(generator_args))) {
    generator_args$auto_plots_theme <- theme
  }

  list(
    OutputPath = output_path,
    OutputFile = output_file,
    Title = title,
    Subtitle = subtitle,
    Theme = theme,
    Open = open,
    Quiet = quiet,
    SelfContained = self_contained,
    RmdFile = rmd_file,
    Package = package,
    TemplatePath = template_path,
    Clean = clean,
    Envir = envir,
    generator_args = generator_args
  )
}

aq_shap_report_template_path <- function(RmdFile, Package, TemplatePath = NULL) {
  if (!is.null(TemplatePath) && nzchar(TemplatePath)) {
    template_path <- normalizePath(TemplatePath, winslash = "/", mustWork = FALSE)
  } else {
    template_path <- system.file("r-markdowns", RmdFile, package = Package)
    if (!nzchar(template_path) || !file.exists(template_path)) {
      template_path <- file.path(getwd(), "inst", "r-markdowns", RmdFile)
      template_path <- normalizePath(template_path, winslash = "/", mustWork = FALSE)
    }
  }
  if (!file.exists(template_path)) {
    template_path <- file.path(getwd(), RmdFile)
    template_path <- normalizePath(template_path, winslash = "/", mustWork = FALSE)
  }
  if (!file.exists(template_path)) {
    stop(
      paste0(
        "RMarkdown template not found. Expected one of:\n",
        "1. ", file.path("inst", "r-markdowns", RmdFile), "\n",
        "2. system.file('r-markdowns', '", RmdFile, "', package = '", Package, "')\n",
        "3. Explicit `TemplatePath`."
      ),
      call. = FALSE
    )
  }
  template_path
}

aq_prepare_regression_shap_report_artifact_result <- function(data = NULL, artifact_result = NULL, generator_args = list()) {
  if (!is.null(artifact_result)) {
    return(artifact_result)
  }
  if (is.null(data)) {
    stop("`data` must be supplied when `artifact_result` is NULL.", call. = FALSE)
  }
  do.call(
    generate_regression_shap_analysis_artifacts,
    c(list(data = data), generator_args)
  )
}

aq_prepare_binary_shap_report_artifact_result <- function(data = NULL, artifact_result = NULL, generator_args = list()) {
  if (!is.null(artifact_result)) {
    return(artifact_result)
  }
  if (is.null(data)) {
    stop("`data` must be supplied when `artifact_result` is NULL.", call. = FALSE)
  }
  do.call(
    generate_binary_classification_shap_analysis_artifacts,
    c(list(data = data), generator_args)
  )
}

aq_validate_shap_report_artifact_result <- function(artifact_result, generator_name) {
  if (!is.list(artifact_result) || is.null(artifact_result$artifacts)) {
    stop(
      paste0("`artifact_result` must be the structured output from ", generator_name, "()."),
      call. = FALSE
    )
  }
  invisible(TRUE)
}

#' Render Regression SHAP Analysis Report
#'
#' Renders a standalone AutoQuant-native HTML report from Regression SHAP
#' Analysis artifacts. If `artifact_result` is not supplied, this function calls
#' `generate_regression_shap_analysis_artifacts()` first. Input data must contain
#' precomputed `Shap_` columns; this report function does not compute SHAP
#' values, call `predict()`, require a model object, or use a SHAP backend
#' package.
#'
#' @param data Optional data.table containing precomputed `Shap_` columns. Used
#'   only when `artifact_result` is NULL.
#' @param artifact_result Optional precomputed result returned by
#'   `generate_regression_shap_analysis_artifacts()`.
#' @param OutputPath Directory where the rendered report should be written.
#' @param OutputFile Output HTML filename.
#' @param Title Report title.
#' @param Subtitle Optional report subtitle.
#' @param Theme Report theme label stored in render params. If `auto_plots_theme`
#'   is not supplied through `...`, this value is also passed to the artifact
#'   generator as `auto_plots_theme`.
#' @param Open If TRUE, open the rendered report in a browser.
#' @param Quiet Passed to `rmarkdown::render()`.
#' @param ... Analytical arguments passed to
#'   `generate_regression_shap_analysis_artifacts()` when `artifact_result` is
#'   NULL, plus optional render controls `self_contained`, `RmdFile`, `Package`,
#'   `TemplatePath`, `Clean`, and `Envir`. Legacy lowercase render names such as
#'   `output_dir`, `output_file`, `title`, `subtitle`, `open`, and `quiet` are
#'   still accepted.
#'
#' @return Invisibly returns the rendered report path.
#'
#' @family Reports
#' @export
RegressionShapAnalysisReport <- function(
  data = NULL,
  artifact_result = NULL,
  OutputPath = getwd(),
  OutputFile = NULL,
  Title = "Regression SHAP Analysis Report",
  Subtitle = NULL,
  Theme = "dark",
  Open = FALSE,
  Quiet = TRUE,
  ...
) {
  if (!requireNamespace("rmarkdown", quietly = TRUE)) {
    stop("Package 'rmarkdown' is required to render RegressionShapAnalysisReport().", call. = FALSE)
  }

  if (!requireNamespace("knitr", quietly = TRUE)) {
    stop("Package 'knitr' is required to render RegressionShapAnalysisReport().", call. = FALSE)
  }

  for (pkg in c("data.table", "htmltools", "reactable", "echarts4r", "AutoPlots")) {
    if (!requireNamespace(pkg, quietly = TRUE)) {
      stop(paste0("Package '", pkg, "' is required to render RegressionShapAnalysisReport()."), call. = FALSE)
    }
  }

  opts <- aq_shap_report_options(
    dots = list(...),
    OutputPath = OutputPath,
    OutputFile = OutputFile,
    Title = Title,
    Subtitle = Subtitle,
    Theme = Theme,
    Open = Open,
    Quiet = Quiet,
    default_output_file = "regression_shap_analysis_report.html",
    default_rmd_file = "Regression_SHAP_Analysis_Report.Rmd"
  )

  artifact_result <- aq_prepare_regression_shap_report_artifact_result(
    data = data,
    artifact_result = artifact_result,
    generator_args = opts$generator_args
  )
  aq_validate_shap_report_artifact_result(artifact_result, "generate_regression_shap_analysis_artifacts")

  output_dir <- normalizePath(opts$OutputPath, winslash = "/", mustWork = FALSE)
  dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)

  template_path <- aq_shap_report_template_path(opts$RmdFile, opts$Package, opts$TemplatePath)

  generated_at <- artifact_result$metadata$generated_at
  if (is.null(generated_at)) {
    generated_at <- Sys.time()
  }

  Envir <- opts$Envir
  if (is.null(Envir)) {
    Envir <- new.env(parent = .GlobalEnv)
  }
  assign("artifact_result", artifact_result, envir = Envir)
  assign("RegressionShapArtifacts", artifact_result, envir = Envir)

  rendered_file <- rmarkdown::render(
    input = template_path,
    output_file = opts$OutputFile,
    output_dir = output_dir,
    params = list(
      title = opts$Title,
      subtitle = opts$Subtitle,
      Theme = opts$Theme,
      generated_at = generated_at,
      artifact_result = artifact_result,
      artifact_sections = regression_shap_sections(),
      metadata = artifact_result$metadata,
      warnings = artifact_result$warnings,
      diagnostics = artifact_result$diagnostics,
      top_n = aq_shap_report_default(opts$generator_args$top_n, 20L),
      include_interactions = aq_shap_report_default(opts$generator_args$include_interactions, FALSE),
      report_args = opts$generator_args
    ),
    envir = Envir,
    quiet = opts$Quiet,
    clean = opts$Clean,
    output_options = list(self_contained = isTRUE(opts$SelfContained))
  )

  rendered_file <- normalizePath(rendered_file, winslash = "/", mustWork = FALSE)
  attr(rendered_file, "artifact_result") <- artifact_result
  if (isTRUE(opts$Open)) {
    utils::browseURL(rendered_file)
  }

  invisible(rendered_file)
}

# ============================================================
# Render Binary Classification SHAP Analysis Report from Artifacts
#
# RMarkdown template expected at:
#   inst/r-markdowns/Binary_Classification_SHAP_Analysis_Report.Rmd
#
# This function renders the AutoQuant-native standalone report path. It calls
# generate_binary_classification_shap_analysis_artifacts() when artifact_result
# is not supplied, but it does not compute SHAP values itself.
# ============================================================

#' Render Binary Classification SHAP Analysis Report
#'
#' Renders a standalone AutoQuant-native HTML report from Binary Classification
#' SHAP Analysis artifacts. If `artifact_result` is not supplied, this function
#' calls `generate_binary_classification_shap_analysis_artifacts()` first. Input
#' data must contain precomputed `Shap_` columns; this report function does not
#' compute SHAP values, call `predict()`, require a model object, or use a SHAP
#' backend package.
#'
#' @param data Optional data.table containing precomputed `Shap_` columns. Used
#'   only when `artifact_result` is NULL.
#' @param artifact_result Optional precomputed result returned by
#'   `generate_binary_classification_shap_analysis_artifacts()`.
#' @param OutputPath Directory where the rendered report should be written.
#' @param OutputFile Output HTML filename.
#' @param Title Report title.
#' @param Subtitle Optional report subtitle.
#' @param Theme Report theme label stored in render params. If `auto_plots_theme`
#'   is not supplied through `...`, this value is also passed to the artifact
#'   generator as `auto_plots_theme`.
#' @param Open If TRUE, open the rendered report in a browser.
#' @param Quiet Passed to `rmarkdown::render()`.
#' @param ... Analytical arguments passed to
#'   `generate_binary_classification_shap_analysis_artifacts()` when
#'   `artifact_result` is NULL, plus optional render controls `self_contained`,
#'   `RmdFile`, `Package`, `TemplatePath`, `Clean`, and `Envir`. Legacy
#'   lowercase render names such as `output_dir`, `output_file`, `title`,
#'   `subtitle`, `open`, and `quiet` are still accepted.
#'
#' @return Invisibly returns the rendered report path.
#'
#' @family Reports
#' @export
BinaryClassificationShapAnalysisReport <- function(
  data = NULL,
  artifact_result = NULL,
  OutputPath = getwd(),
  OutputFile = NULL,
  Title = "Binary Classification SHAP Analysis Report",
  Subtitle = NULL,
  Theme = "dark",
  Open = FALSE,
  Quiet = TRUE,
  ...
) {
  if (!requireNamespace("rmarkdown", quietly = TRUE)) {
    stop("Package 'rmarkdown' is required to render BinaryClassificationShapAnalysisReport().", call. = FALSE)
  }
  if (!requireNamespace("knitr", quietly = TRUE)) {
    stop("Package 'knitr' is required to render BinaryClassificationShapAnalysisReport().", call. = FALSE)
  }
  for (pkg in c("data.table", "htmltools", "reactable", "echarts4r", "AutoPlots")) {
    if (!requireNamespace(pkg, quietly = TRUE)) {
      stop(paste0("Package '", pkg, "' is required to render BinaryClassificationShapAnalysisReport()."), call. = FALSE)
    }
  }

  opts <- aq_shap_report_options(
    dots = list(...),
    OutputPath = OutputPath,
    OutputFile = OutputFile,
    Title = Title,
    Subtitle = Subtitle,
    Theme = Theme,
    Open = Open,
    Quiet = Quiet,
    default_output_file = "binary_classification_shap_analysis_report.html",
    default_rmd_file = "Binary_Classification_SHAP_Analysis_Report.Rmd"
  )

  artifact_result <- aq_prepare_binary_shap_report_artifact_result(
    data = data,
    artifact_result = artifact_result,
    generator_args = opts$generator_args
  )
  aq_validate_shap_report_artifact_result(artifact_result, "generate_binary_classification_shap_analysis_artifacts")

  output_dir <- normalizePath(opts$OutputPath, winslash = "/", mustWork = FALSE)
  dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)

  template_path <- aq_shap_report_template_path(opts$RmdFile, opts$Package, opts$TemplatePath)

  generated_at <- artifact_result$metadata$generated_at
  if (is.null(generated_at)) {
    generated_at <- Sys.time()
  }

  Envir <- opts$Envir
  if (is.null(Envir)) {
    Envir <- new.env(parent = .GlobalEnv)
  }
  assign("artifact_result", artifact_result, envir = Envir)
  assign("BinaryClassificationShapArtifacts", artifact_result, envir = Envir)

  rendered_file <- rmarkdown::render(
    input = template_path,
    output_file = opts$OutputFile,
    output_dir = output_dir,
    params = list(
      title = opts$Title,
      subtitle = opts$Subtitle,
      Theme = opts$Theme,
      generated_at = generated_at,
      artifact_result = artifact_result,
      artifact_sections = binary_shap_sections(),
      metadata = artifact_result$metadata,
      warnings = artifact_result$warnings,
      diagnostics = artifact_result$diagnostics,
      top_n = aq_shap_report_default(opts$generator_args$top_n, 20L),
      include_interactions = aq_shap_report_default(opts$generator_args$include_interactions, TRUE),
      report_args = opts$generator_args
    ),
    envir = Envir,
    quiet = opts$Quiet,
    clean = opts$Clean,
    output_options = list(self_contained = isTRUE(opts$SelfContained))
  )

  rendered_file <- normalizePath(rendered_file, winslash = "/", mustWork = FALSE)
  attr(rendered_file, "artifact_result") <- artifact_result
  if (isTRUE(opts$Open)) {
    utils::browseURL(rendered_file)
  }

  invisible(rendered_file)
}

#' QA SHAP Report Wrapper Contracts
#'
#' Validates that the SHAP report wrappers use the generator-first contract:
#' report functions accept concise rendering arguments, analytical arguments pass
#' through `...`, and supplied artifact results are reused without recomputing.
#'
#' @return A data.table of QA checks.
#'
#' @family QA
#' @export
qa_shap_report_wrapper_contracts <- function() {
  if (!requireNamespace("data.table", quietly = TRUE)) {
    stop("Package 'data.table' is required for qa_shap_report_wrapper_contracts().", call. = FALSE)
  }

  set.seed(42)
  n <- 80L
  reg_dt <- data.table::data.table(
    Target = stats::rnorm(n),
    Predict = stats::rnorm(n),
    Date = as.Date("2024-01-01") + sample(0:90, n, TRUE),
    Segment = sample(c("A", "B"), n, TRUE),
    FeatureA = stats::runif(n),
    FeatureB = stats::rnorm(n)
  )
  reg_dt[, Shap_FeatureA := 0.15 * FeatureA + stats::rnorm(.N, 0, 0.01)]
  reg_dt[, Shap_FeatureB := 0.05 * FeatureB + stats::rnorm(.N, 0, 0.01)]

  bin_dt <- data.table::copy(reg_dt)
  bin_dt[, Target := sample(c("Yes", "No"), .N, TRUE)]
  bin_dt[, Predict := stats::runif(.N)]
  bin_dt[, PredictedClass := ifelse(Predict >= 0.5, "Yes", "No")]

  reg_artifacts <- generate_regression_shap_analysis_artifacts(
    data = reg_dt,
    target_col = "Target",
    prediction_col = "Predict",
    DateVar = "Date",
    ByVars = "Segment",
    selected_features = c("FeatureA", "FeatureB"),
    top_n = 2L,
    include_plots = FALSE
  )
  bin_artifacts <- generate_binary_classification_shap_analysis_artifacts(
    data = bin_dt,
    target_col = "Target",
    prediction_col = "Predict",
    predicted_class_col = "PredictedClass",
    positive_class = "Yes",
    prediction_scale = "probability",
    threshold = 0.5,
    DateVar = "Date",
    ByVars = "Segment",
    selected_features = c("FeatureA", "FeatureB"),
    top_n = 2L,
    include_plots = FALSE
  )

  bad_dt <- data.table::data.table(NotShap = 1:3)
  reused_reg <- suppressWarnings(aq_prepare_regression_shap_report_artifact_result(
    data = bad_dt,
    artifact_result = reg_artifacts,
    generator_args = list(target_col = "Missing")
  ))
  reused_bin <- suppressWarnings(aq_prepare_binary_shap_report_artifact_result(
    data = bad_dt,
    artifact_result = bin_artifacts,
    generator_args = list(target_col = "Missing", positive_class = "Yes")
  ))

  direct_reg <- aq_prepare_regression_shap_report_artifact_result(
    data = reg_dt,
    artifact_result = NULL,
    generator_args = list(
      target_col = "Target",
      prediction_col = "Predict",
      DateVar = "Date",
      ByVars = "Segment",
      selected_features = c("FeatureA", "FeatureB"),
      top_n = 2L,
      include_plots = FALSE
    )
  )
  direct_bin <- aq_prepare_binary_shap_report_artifact_result(
    data = bin_dt,
    artifact_result = NULL,
    generator_args = list(
      target_col = "Target",
      prediction_col = "Predict",
      predicted_class_col = "PredictedClass",
      positive_class = "Yes",
      prediction_scale = "probability",
      threshold = 0.5,
      DateVar = "Date",
      ByVars = "Segment",
      selected_features = c("FeatureA", "FeatureB"),
      top_n = 2L,
      include_plots = FALSE
    )
  )

  reg_formals <- names(formals(RegressionShapAnalysisReport))
  bin_formals <- names(formals(BinaryClassificationShapAnalysisReport))
  expected_formals <- c("data", "artifact_result", "OutputPath", "OutputFile", "Title", "Subtitle", "Theme", "Open", "Quiet", "...")
  legacy_opts <- aq_shap_report_options(
    dots = list(output_dir = tempdir(), output_file = "legacy", title = "Legacy", quiet = FALSE, target_col = "Target"),
    OutputPath = getwd(),
    OutputFile = NULL,
    Title = "Default",
    Subtitle = NULL,
    Theme = "dark",
    Open = FALSE,
    Quiet = TRUE,
    default_output_file = "default.html",
    default_rmd_file = "Regression_SHAP_Analysis_Report.Rmd"
  )

  reg_template <- aq_shap_report_template_path("Regression_SHAP_Analysis_Report.Rmd", "AutoQuant", NULL)
  bin_template <- aq_shap_report_template_path("Binary_Classification_SHAP_Analysis_Report.Rmd", "AutoQuant", NULL)
  readme <- if (file.exists("README.md")) paste(readLines("README.md", warn = FALSE), collapse = "\n") else ""

  checks <- data.table::data.table(
    check = c(
      "regression_signature_simplified",
      "binary_signature_simplified",
      "regression_artifact_result_reused",
      "binary_artifact_result_reused",
      "regression_direct_data_dots_generated",
      "binary_direct_data_dots_generated",
      "legacy_render_aliases_removed_from_generator_args",
      "legacy_analytical_args_preserved",
      "regression_template_found",
      "binary_template_found",
      "readme_generator_first_example_present",
      "readme_convenience_example_present"
    ),
    status = c(
      if (identical(reg_formals, expected_formals)) "success" else "error",
      if (identical(bin_formals, expected_formals)) "success" else "error",
      if (identical(reused_reg, reg_artifacts)) "success" else "error",
      if (identical(reused_bin, bin_artifacts)) "success" else "error",
      if (is.list(direct_reg) && !is.null(direct_reg$artifacts)) "success" else "error",
      if (is.list(direct_bin) && !is.null(direct_bin$artifacts)) "success" else "error",
      if (!any(c("output_dir", "output_file", "title", "quiet") %in% names(legacy_opts$generator_args))) "success" else "error",
      if (identical(legacy_opts$generator_args$target_col, "Target")) "success" else "error",
      if (file.exists(reg_template)) "success" else "error",
      if (file.exists(bin_template)) "success" else "error",
      if (grepl("artifact_result = reg_artifacts", readme, fixed = TRUE) && grepl("artifact_result = binary_artifacts", readme, fixed = TRUE)) "success" else "error",
      if (grepl("Convenience wrapper", readme, fixed = TRUE)) "success" else "error"
    ),
    message = c(
      paste(reg_formals, collapse = ", "),
      paste(bin_formals, collapse = ", "),
      "Regression artifact_result path returns the supplied object.",
      "Binary artifact_result path returns the supplied object.",
      paste0("Regression artifacts: ", length(direct_reg$artifacts)),
      paste0("Binary artifacts: ", length(direct_bin$artifacts)),
      "Legacy render aliases are consumed by report options.",
      "Analytical arguments remain in generator_args.",
      reg_template,
      bin_template,
      "README includes artifact_result renderer examples.",
      "README includes data + ... convenience wrapper examples."
    )
  )

  checks
}
