# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

QRGibbsSim <- function(CountScore, SizeScore, CountList, SizeList, nSims) {
    .Call('_RemixAutoML_QRGibbsSim', PACKAGE = 'RemixAutoML', CountScore, SizeScore, CountList, SizeList, nSims)
}

